### ISSUE TITLE
Crash on Launch for v174

### ISSUE THREAD

**Issue by threeohclock** [Rem0o/FanControl.Releases#2136] opened 2023-11-22 07:10 UTC
**Describe the bug**

FanControl v174 crashes at launch time.  The following is the stack trace from Event Viewer:
```
Application: FanControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at FanControl.App.LogUnhandledException(FanControl.Domain.ILogger, FanControl.Domain.IDialogService, System.Exception, System.String)
   at FanControl.App.<SetupExceptionHandling>b__18_1(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)
   at System.Windows.Threading.Dispatcher.CatchException(System.Exception)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at FanControl.App.Main()
```

v173 does not exhibit the error.

**Is there a log.txt file next to FanControl.exe with recent date entries?**

No log.txt entry is added.

**Relevant hardware specs and setup**

See http://www.datavortex.net/tritium

**Comment by essinghigh** [comment] 2023-11-22 07:23
Possibly a duplicate of #2135, have you manually downloaded FanControl and extracted it over the existing installation?
I see the same in event viewer on my end, works after I updated manually.

**Comment by GuruSR** [comment] 2023-11-22 12:54
**FIX:**  After the failed update, browse to the FanControl folder, manually delete Newtonsoft.Json.dll and then run the Updater.exe, the problem solves itself.

**Comment by Rem0o** [comment] 2023-11-22 13:03
The update process is broken due to a defender false positive flagging the exe as it tries to download the zip/new version.  False positive submission should go through at some point, sorry for the inconvenience. 

Rolled back to the old updater for the time being as I figures this one out, until then you can do as @
essinghigh  mentionned.

**Closed** 2023-12-29 22:04 UTC
