### ISSUE TITLE
Run on Windows start before user log in (as service) with separate GUI executable

### ISSUE THREAD

**Issue by nightrider77** [Rem0o/FanControl.Releases#2871] opened 2024-12-14 14:33 UTC
Hello.

I have Huananzhi X99-F8 (v2), its BIOS incorrectly reading CPU temp, so it can't automatically adjust CPU fan RPM.
Your utility did the trick - all temperatures show correctly and CPU fan adjustment works! Thanks.

The only one problem is that I have another PC user without administrative rights.
I set up scheduler job with elevated rights to run FanControl when PC boots up.
When any user logs in, app is running and does its job fine! But there is no tray icon of FanControl available.

It will be great to make FanControl to run as service.
And to make the separate executable for GUI. If you run it (e.g. FanControl_ui.exe) (no difference how - through shortcut, icon in task bar or explorer), it will open its UI.
If user doesn't have admin rights, it will open in read only mode with notification that "UI runs in read only mode" with Open as Admin button somewhere on top. If user does have admin rights, it will run in normal mode.

Thanks.

**Comment by Rem0o** [comment] 2024-12-15 18:27
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/135

**Closed by Rem0o** 2024-12-15 18:27 UTC
