### ISSUE TITLE
Fan Control V124 window affects refresh rate on W10 destop and games

### ISSUE THREAD

**Issue by AmbientHorst** [Rem0o/FanControl.Releases#1056] opened 2022-08-29 18:16 UTC
**Fan Control V124 window affects refresh rate on W10 desktop and games while opened**
The main window of V124 reproducibly lets the monitor refresh rate drop to 48-60hz from 170hz whenever it is opened and randomly produces this behaviour in games (borderless windowed) when running in the background. When the window is closed to tray this does not occur.

**Relevant hardware specs and setup**
Fan Control V124
Windows 10 21H2
GeForce Game Ready driver 516.94

G-Sync: "Enable for windowed and fullscreen mode" in Nvidia control panel

RTX 3090
MSI PRO Z690-A DDR4
Intel 12600KF

**Comment by Rem0o** [comment] 2022-08-29 19:32
Does this issue matches yours? 

https://github.com/dotnet/wpf/issues/2294

**Comment by AmbientHorst** [comment] 2022-08-30 00:44
Yes, with the addition that the Fan Control GUI seems to hook VRR in a privileged way that occasionaly forces the refresh rate to drop in (at least borderless windowed) games without the Fan Control window even visible.

Aug 29, 2022 21:32:17 Rem0o ***@***.***>:

**Comment by Rem0o** [comment] 2022-08-30 00:46
There seem to be a few workaround in the post I linked. The issue is still opened and not addressed in the base wpf framework.  Not much I can do.

**Comment by AmbientHorst** [comment] 2022-08-30 02:09
Ok thanks a lot. I appreciate your work, this is a magnificent project.

Aug 30, 2022 02:47:08 Rem0o ***@***.***>:

**Closed** 2022-09-03 18:40 UTC
