### ISSUE TITLE
FanControl.exe triggering Easy Anti-Cheat

### ISSUE THREAD

**Issue by AnotherOddity** [Rem0o/FanControl.Releases#2544] opened 2024-06-01 16:33 UTC
**Describe the bug**
While playing games, fan control triggered Easy Anti-Cheat. 
Given that it's somewhat widespread in games, and I'd guess most users of FanControl are gamers, I imagine it's worth being aware.
---

**Relevant hardware specs and setup**
Windows 10 Pro
Ryzen 5800X
RX580
F35 version Gigabyte BIOS

**Error message**
![image](https://github.com/Rem0o/FanControl.Releases/assets/18012978/e2fff8d5-961b-4c53-9d79-e161bebf9944)
Triggered while in war thunder, if that's relevant.

**Comment by Rem0o** [comment] 2024-06-01 16:54
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/2104

**Closed by Rem0o** 2024-06-01 16:54 UTC
