### ISSUE TITLE
V190 broken (doesent work anymore)

### ISSUE THREAD

**Issue by 70V07** [Rem0o/FanControl.Releases#2510] opened 2024-05-15 01:17 UTC
**OTHER INFOS** 190 version 8.0 .NET (potable)

**BUG** nothing work... no sensors on GPU (I use FanControl only for GPU)

[FanControl_15.05.02024_log.txt](https://gist.github.com/70V07/07a81b918c35e1469d28423c08940836)

**AMD driver version:** 31.0.12027.9001
**GPU:** MSI ARMOR OC RX 580 8GB
**OS:** Windows 10 Professional

driver version is from Microsoft Windows Updarte why I have other problems with latest drivers from AMD site (like black screeen) and no problem with this version... except FanControl after this update

![Untitled](https://github.com/Rem0o/FanControl.Releases/assets/46967291/b6cbe43a-5a30-4f12-99ec-fc1c06a51212)

**Comment by stl3** [comment] 2024-05-15 02:17
I can confirm on my end it also does not detect whereas @V189 worked. Getting same issue as above. 
AMD driver: 22.61
GPU: HD7970
OS: Win 21H2 19043.4291
PS - how do I get back to the other version? `scoop install fancontrol@V189` doesn't work, or I assume I'm doing it incorrectly.

**Comment by Rem0o** [comment] 2024-05-15 02:28
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/2509

**Closed** 2024-05-15 02:28 UTC
