### ISSUE TITLE
Can't install newest Update. 

### ISSUE THREAD

**Issue by LamarDavis990** [Rem0o/FanControl.Releases#2140] opened 2023-11-22 09:40 UTC
I didn't think I'd be able to properly explain my issue over text so I just made a video and uploaded it to Google Drive so anyone can watch. Any help would be very appreciated I am VERY new to PC stuff and do not know a lot about this kinda stuff in general. 

https://drive.google.com/file/d/10yOH5hcpC5SmA5VE3qsCcEH22RNZAlC-/view?usp=drivesdk

**Comment by knuthen** [comment] 2023-11-22 09:52
You have to go back into "Virus & threat protection" click on "protection history" and then on the notification which marks "...Fancontrol\updater.exe" as a threat and hit restore.
After that you should be able to re-run the fancontrol updater

**Comment by Naocum** [comment] 2023-11-22 10:05
> You have to go back into "Virus & threat protection" click on "protection history" and then on the notification which marks "...Fancontrol\updater.exe" as a threat and hit restore. After that you should be able to re-run the fancontrol updater

Is this a false positive? Why ignore such a thing when the update is introduced literally a few hours ago?

**Comment by knuthen** [comment] 2023-11-22 10:07
> > You have to go back into "Virus & threat protection" click on "protection history" and then on the notification which marks "...Fancontrol\updater.exe" as a threat and hit restore. After that you should be able to re-run the fancontrol updater
> 
> Is this a false positive? Why ignore such a thing when the update is introduced literally a few hours ago?

![grafik](https://github.com/Rem0o/FanControl.Releases/assets/11912128/fa7fa9dc-c197-4f0e-be67-5756e6442672)
According to the releases notes, it is indeed a false positive. IF you want to be sure, stick to the old version until you are certain that you can trust the update.

**Comment by LamarDavis990** [comment] 2023-11-22 10:11
> You have to go back into "Virus & threat protection" click on "protection history" and then on the notification which marks "...Fancontrol\updater.exe" as a threat and hit restore. After that you should be able to re-run the fancontrol updater

I'm gonna be honest I'm not sure how but I somehow deleted fancontrol so I just reinstalled it but now I'm getting this.
![20231122_041034](https://github.com/Rem0o/FanControl.Releases/assets/151726650/f9fc928e-91a1-463c-b980-13973ef69b24)

I have no clue what I should do now. If it's been flagged twice.

**Comment by knuthen** [comment] 2023-11-22 10:14
https://github.com/Rem0o/FanControl.Releases/releases
here you can always find older versions on fancontrol, means you can download the 173 or even 172.
I had the same popup, but ran it anyway. As stated in the release not, it takes some time until windows defender stops flagging it as a false positive.

**Comment by LamarDavis990** [comment] 2023-11-22 10:18
> https://github.com/Rem0o/FanControl.Releases/releases here you can always find older versions on fancontrol, means you can download the 173 or even 172. I had the same popup, but ran it anyway. As stated in the release not, it takes some time until windows defender stops flagging it as a false positive.

Fair enough as long as people trust it I'll just run it then. My fans get annoying as hell without a curve so kinda redundant anyways.

**Comment by noviceg** [comment] 2023-11-22 10:34
restored update.exe, excluded fancontrol folder from windows defender and now the auto update is broken, even if I download an older version and try to update it, i will be getting this error

![image](https://i.imgur.com/iI908Rz.png)

**Comment by LamarDavis990** [comment] 2023-11-22 10:36
> restored update.exe, excluded fancontrol folder from windows defender and now the auto update is broken, even if I download an older version and try to update it, i will be getting this error
> 
> ![image](https://camo.githubusercontent.com/2904a1beec05ddb4ee7fe57580652f46ec5e193a7d00a552e8268114f329753e/68747470733a2f2f692e696d6775722e636f6d2f6949393038527a2e706e67)

That's exactly the message I had, I tried to fix it by messing with some files but I ended up deleted fancontrol on accident and reinstalled. Honestly that might just be the easiest fix for it.

**Comment by fshelton79** [comment] 2023-11-22 11:20
I manually downloaded the V174 release and extracted to the same directory telling it to overwrite everything. This kept my config intact.

**Comment by BluntedR** [comment] 2023-11-22 11:32
Rename 
![image](https://github.com/Rem0o/FanControl.Releases/assets/108763386/2a10861c-6d18-40a4-830b-71e845b3a44e)

Run 
![image](https://github.com/Rem0o/FanControl.Releases/assets/108763386/8c2fcdce-c311-4721-874e-dc7cc38888a6)

Enjoy?

**Comment by DeLawrence** [comment] 2023-11-22 11:37
> Hello, How I fixed my issue with Microsoft Defender issue : 1/ backup your userConfig.json ( directory : C:\Users\xxx\Desktop\FanControl (1)\Configurations\ ) 2/ delete the FanControl folder 3/ download the latest archive ( https://github.com/Rem0o/FanControl.Releases ) 4/ load the backed up config file , restart the tool, and all works

I had to also edit the version in the config file from 173 to 174, otherwise it wouldn't load.

**Comment by noviceg** [comment] 2023-11-22 11:38
> Rename ![image](https://user-images.githubusercontent.com/108763386/284889177-2a10861c-6d18-40a4-830b-71e845b3a44e.png)
> 
> Run ![image](https://user-images.githubusercontent.com/108763386/284889247-8c2fcdce-c311-4721-874e-dc7cc38888a6.png)
> 
> Enjoy?

it works, thanks 👍

**Comment by Peca21** [comment] 2023-11-22 11:44
I just deleted JONS dll and ran the updater and it updated fine.

**Comment by Rem0o** [comment] 2023-11-22 13:07
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/2135

**Closed by Rem0o** 2023-11-22 13:07 UTC
