### ISSUE TITLE
No Alarms, two sets of fans failed. No warning.

### ISSUE THREAD

**Issue by 9812ga98sd** [Rem0o/FanControl.Releases#2723] opened 2024-09-11 17:38 UTC
Why is there no alarm, the most basic function of a good fan controller, in this application?
I had two sets of fans stop working and only noticed as the room was very hot. 
When RPM is zero have the option to flash the icon on the taskbar or a warning message.

What is the point of a fan control application if it gives no warnings?

**Comment by Rem0o** [comment] 2024-09-12 00:21
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/807.
It's in the pipes.

> What is the point of a fan control application if it gives no warnings?

To control your fans with fan curves?

**Closed** 2024-09-12 01:05 UTC

**Comment by 9812ga98sd** [comment] 2024-09-12 09:57
> Duplicate of #807. It's in the pipes.
> 
> Closing this.
> 
> > What is the point of a fan control application if it gives no warnings?
> 
> To control your fans with curves?
> 
> Also, just curious, how does 2 sets (2x2=4?) of fans fail at + or - the same time?

"To control your fans with curves?"

The problem with current tech people is they dont have decades of experience grounded in hardware/software.

"Also, just curious, how does 2 sets (2x2=4?) of fans fail at + or - the same time?"

See above.

2 cables failed due to solder drying out and not using correct crimping on the wire.
