### ISSUE TITLE
Issue reading HWiNFO64 sensors on startup

### ISSUE THREAD

**Issue by chjohans** [Rem0o/FanControl.Releases#357] opened 2021-10-14 01:27 UTC
I've been using FanControl for a few months, and for a few weeks the HSINFO plugin to enable more sensors. It's an excellent combo as I'm now able to control my GPU radiator fans based on my GPU temperature, and my additional GPU backplate cooling fans based on my GPU VRAM temperature.

Anyhow, since I installed the HWiNFO plugin I get the error message as in the attached screenshot almost every time I start FanControl, it does not matter much if it's started by the Task Scheduler task for autostart with windows, or if I manually start it. Except that it seemed to happen slightly less often when I delayed the Task Scheduler task to 1 minute, but that is automatically overwritten by FanControl on every reboot. I understand the need to check if the task exists based on the "start with windows flag", what I don't understand is why it has to be overwritten when I have edited it for a slightly longer delay. It's not always true that "one shoe fits them all". Anyhow, the delay does not make much of a difference, but initially, I thought so.

I don't want FanControl to overwrite my settings, because if I let it do that I will have to configure those HWINFO sensors and how fans react to them all over again.

After I dismiss the error message FanControl will ask:

Do you want to refresh? Yes/No

If I click "Yes" it will sometimes refresh the sensors and find those missing HWINFO sensors, end sometimes it won't. It's about 50/50, so about half the time it will find the sensors and half the time it will just show the same error message again. But it will eventually always find the sensors every single time as long as I repeat this enough times, and it has so far never taken longer than 5 tries clicking on "Yes" when asked "Do you want to refresh?". And when it works it will work fine until my next reboot, when the same thing usually (but not always) will happen again. Other than this issue it seems like FanControl is reading the HWINFO sensors just fine, but this bug is really annoying.

I am thinking maybe the issue is some kind of timing/timeout issue between FanControl and the HWINFO plugin? Or at least that's what the symptoms look like to me.

Could you please have a look into this? And I'll be more than happy to assist with further debugging/testing.

I am using the latest versions of both FanControl (V94) and HWiNFO (7.12-4580), "Shared memory" is of course in HWiNFO and I do have a "Pro" license for HWiNFO64.

**Comment by Rem0o** [comment] 2021-10-14 01:43
Duplicate of https://github.com/Rem0o/FanControl.HWInfo/issues/7#issuecomment-942856821

**Closed by Rem0o** 2021-10-14 01:43 UTC
