### ISSUE TITLE
Multiple temperatures in a system tray

### ISSUE THREAD

**Issue by Eldenroot** [Rem0o/FanControl.Releases#23] opened 2020-08-23 17:31 UTC
Screenshot below:
![image](https://user-images.githubusercontent.com/778890/90984730-29994180-e577-11ea-8cf3-1c9a03526ffd.png)

Select more temps which would be displayed in the system tray

**Comment by OlympicLarry** [comment] 2020-09-30 18:47
+1

**Comment by Nickneem** [comment] 2020-11-03 23:27
+1

**Comment by JarrettWendt** [comment] 2020-11-25 03:11
+1

**Comment by pigsodomizer** [comment] 2021-03-24 20:26
+1

**Comment by Rem0o** [comment] 2022-07-21 22:35
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/38

**Closed by Rem0o** 2022-07-21 22:35 UTC
