### ISSUE TITLE
FEATURE REQUEST: Application Curve

### ISSUE THREAD

**Issue by nikolicjakov** [Rem0o/FanControl.Releases#923] opened 2022-07-06 10:11 UTC
Hi there,

i have just installed your FanControl software and i am loving it. But it would be nice to have application curve so when i start my game i can set static fan speed that would keep my pc loud and cool but when i am done with gaming i would like to have my fans silent.

I hope there is no same request here.

**Comment by Rem0o** [comment] 2022-07-06 13:15
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/97

**Closed by Rem0o** 2022-07-06 13:15 UTC
