### ISSUE TITLE
v82 and higher won't recognize sensors anymore

### ISSUE THREAD

**Issue by kbolte** [Rem0o/FanControl.Releases#268] opened 2021-06-19 23:14 UTC
Since update v82 (could be one or two earlier, not sure when I last updated before v82), only my GPU sensors are recognized, but non of my system or CPU sensors are. Getting a lot of "Missing speed sensor:..." errors. These don't go away with "refresh".

I downloaded v78 and everything works flawlessly there.

Got a MSI B550 Tomahawk, Ryzen 5900X and a RTX 3080 Founders Edition.

Here's a screenshot of the errors:

![FanControlErrors](https://user-images.githubusercontent.com/55092287/122657540-a6c81f80-d164-11eb-9d99-3a9970b5b100.png)

Edit: Here's my config:

`{
  "Main": {
    "DisplayTrayIconTemperature": true,
    "ShowHiddenCards": false,
    "HideFanSpeedCards": false,
    "StartMinimized": true,
    "FanCurves": [
      {
        "IdleFanSpeed": 40,
        "LoadFanSpeed": 55,
        "IdleTemperature": 40,
        "LoadTemperature": 80,
        "SelectedTempSource": {
          "Name": "Core (Tctl/Tdie)",
          "Identifier": "/amdcpu/0/temperature/2",
          "IsHidden": false
        },
        "SelectedResponseTime": 1,
        "Name": "Target"
      },
      {
        "Percent": 32,
        "Name": "Pump"
      },
      {
        "Percent": 100,
        "Name": "OFF"
      },
      {
        "Points": [
          "20,32.6116767939815",
          "40,32.6116767939815",
          "60,32.8338990162037",
          "70,44.6116767939815",
          "80,49.7227879050926",
          "90,90.167232349537"
        ],
        "SelectedTempSource": {
          "Name": "Core (Tctl/Tdie)",
          "Identifier": "/amdcpu/0/temperature/2",
          "IsHidden": false
        },
        "SelectedHysteresis": 2,
        "SelectedResponseTime": 4,
        "OneWayHysteresis": false,
        "Name": "Graph"
      },
      {
        "Points": [
          "20,25.5005656828704",
          "40,26.167232349537",
          "60,26.167232349537",
          "70,40.6116767939815",
          "80,49.7227879050926",
          "90,90.167232349537"
        ],
        "SelectedTempSource": {
          "Name": "Core (Tctl/Tdie)",
          "Identifier": "/amdcpu/0/temperature/2",
          "IsHidden": false
        },
        "SelectedHysteresis": 2,
        "SelectedResponseTime": 4,
        "OneWayHysteresis": false,
        "Name": "Graph 1"
      }
    ],
    "Controls": [
      {
        "Enable": false,
        "ManualControlValue": 50,
        "ManualControl": false,
        "MatchingFanSensor": null,
        "SelectedFanCurve": {
          "Percent": 100,
          "Name": "OFF"
        },
        "SelectedOffset": 0,
        "SelectedStart": 0,
        "SelectedStop": 0,
        "SelectedCommandStepUp": 8.0,
        "SelectedCommandStepDown": 8.0,
        "CancelMatchFanCommand": null,
        "Name": "Control 1 - NVIDIA GeForce RTX 3080",
        "NickName": "Control 1 - GeForce RTX 3080",
        "Identifier": "NVApiWrapper/11008/control/0",
        "IsHidden": false,
        "SelectSensorCommand": null
      },
      {
        "Enable": false,
        "ManualControlValue": 50,
        "ManualControl": false,
        "MatchingFanSensor": null,
        "SelectedFanCurve": {
          "Percent": 100,
          "Name": "OFF"
        },
        "SelectedOffset": 0,
        "SelectedStart": 0,
        "SelectedStop": 0,
        "SelectedCommandStepUp": 8.0,
        "SelectedCommandStepDown": 8.0,
        "CancelMatchFanCommand": null,
        "Name": "Control 2 - NVIDIA GeForce RTX 3080",
        "NickName": "Control 2 - GeForce RTX 3080",
        "Identifier": "NVApiWrapper/11008/control/1",
        "IsHidden": false,
        "SelectSensorCommand": null
      }
    ],
    "FanSensors": [
      {
        "IsHidden": false,
        "SelectSensorCommand": null,
        "NickName": "Fan 1 - GeForce RTX 3080",
        "Name": "Fan 1 - NVIDIA GeForce RTX 3080",
        "Identifier": "NVApiWrapper/11008/fan/0"
      },
      {
        "IsHidden": false,
        "SelectSensorCommand": null,
        "NickName": "Fan 2 - GeForce RTX 3080",
        "Name": "Fan 2 - NVIDIA GeForce RTX 3080",
        "Identifier": "NVApiWrapper/11008/fan/1"
      }
    ],
    "CustomSensors": [],
    "SelectedTrayIconSensor": {
      "Name": "Core (Tctl/Tdie)",
      "Identifier": "/amdcpu/0/temperature/2",
      "IsHidden": false
    },
    "SelectedTheme": "",
    "PrimaryColor": "#FF607D8B",
    "SecondaryColor": "#FFAEEA00",
    "SyncThemeWithWindows": false,
    "DisableStorageSensors": false
  }
}`

**Comment by sofyanet** [comment] 2021-06-20 04:48
Duplicate of #264

**Closed** 2021-06-21 01:04 UTC
