### ISSUE TITLE
Feature Request: Activate Fan Settings when process is running

### ISSUE THREAD

**Issue by marcoh242** [Rem0o/FanControl.Releases#1120] opened 2022-09-21 15:04 UTC
I think it would be a nice Feature to activate Fan Settings if a selected Process is running. For example if a benchmark or game is running fans speed up.

**Comment by Rem0o** [comment] 2022-09-21 17:06
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/97.

**Closed by Rem0o** 2022-09-21 17:06 UTC
