### ISSUE TITLE
System.ArgumentOutOfRangeException: Index must be within the bounds of the List.

### ISSUE THREAD

**Issue by emreaktrk** [Rem0o/FanControl.Releases#649] opened 2022-04-24 05:47 UTC
Reproduce Steps:
- Show hidden cards unchecked in hamburger menu
- Move first any (controls, speeds, curves) material card to last one

I attached [log.txt](https://github.com/Rem0o/FanControl.Releases/files/8549076/log.txt)

Thank you for this masterpiece software.
Cheers

**Comment by Rem0o** [comment] 2022-04-24 14:54
Yup, can reproduce.
Dumb index logic from the collection because the "move" action actually copies, then remove the original location, which messes up the indexes.

**Comment by Rem0o** [comment] 2022-05-06 17:11
Fixed in 112.

**Closed by Rem0o** 2022-05-06 17:11 UTC
