### ISSUE TITLE
(gpu-) hysteresis not working (on the way down)

### ISSUE THREAD

**Issue by ownlyme** [Rem0o/FanControl.Releases#1203] opened 2022-10-25 00:41 UTC
Today i started using fan control for my gpu fans instead of afterburner.
When i was done gaming and the temperature crossed the 0 rpm treshold, the fans turned off immediately.
After that, every time the gpu woke up from it's idle power state and spiking the temperature for a second, the fans correctly turned on again, but didn't wait until the temperature dropped by 15° again as i specified.

i tried it with versions 132 and 133

https://imgur.com/a/yiCjw1u
(afterburner hardware monitor shows temperature, power and fan rpm)

**Comment by Rem0o** [comment] 2022-10-25 03:38
Hysteresis is ignored crossing the limits towards them. That's by design. 

Limits are the first and last point of a graph.

Meaning from a high value towards the lower limit and from a low value towards the upper limit.  
This is done so that hysteresis doesn't prevent these values from getting reached, which would be frequent with higher hysteresis values. Often limit values are set at idle point or load point, which won't be crossed by much, leading hysteresis to never trigger if the last set point is close to that limit.

One way to hijack that behavior is with a graph. Simply duplicate your limit points so that the dupplicated "limits" are out of bound of real temperature values.

**Comment by ownlyme** [comment] 2022-10-25 08:34
I'm not sure if i can understand your reasoning.
Afterburner's hysteresis works just like you'd expect.
This bug is also dangerous for the fans, the lack of hysteresis in it's firmware literally ruined my last gpu's fans which started getting a rattling sound after playing factorio for a few hundret hours while constantly starting to spin and going back to idle mode every 3 seconds...

Anyway, your workaround seems to work.
Thank you

**Comment by ownlyme** [comment] 2022-10-26 01:46
"a 15C hysteresis on a +-25 deg range of values in a graph is huge"
- if i let it cool down by 15°, it won't leave it's idle state again for like 15 minutes while only browsing the web
- light gaming barely heats up the card, for example in northgard this lets it stay at ~45° so it doesnt cycle between idle and spinning every 30 seconds
- when playing a AAA game and the card is running over 70°, as soon as you hit a loading screen the fan will slow down because it immediately drops by 10° plus 1° per 5 seconds or so. (so the card doesn't reach those dangerous 76° again in the current session)

"with such a big jump of fan speed"
my gpu has some really weird behavior with the fan curve, 40% is ~500 (unstable), 50% is 900 rpm, 60% is 1370 and so on...
i agree the spinup is pretty abrupt, the card's firmware can do it much more smoothly but no idea how i could achieve that.

anyway, your trick with setting the very first point in the graph to 0°->0% made the hysteresis work. i just don't get why the software would see this as something different.

**Comment by Rem0o** [comment] 2022-10-26 02:39
> my gpu has some really weird behavior with the fan curve, 40% is ~500 (unstable), 50% is 900 rpm, 60% is 1370 and so on...

Try to set a step up% of like 4-5%. It should smooth it out.

**Comment by ownlyme** [comment] 2022-10-26 10:34
the step up doesn't really help that (1%, 4%, 7%...) and if i set the start speed too low it won't start spinning at all.
the ramp up looks like this:
https://imgur.com/a/rtFDRwb
first one is firmware ramp up, second one is fan control (afterburner looks the same)

**Comment by Rem0o** [comment] 2022-10-26 11:52
Very peculiar card behaviour it seems like indeed. 

Closing.

**Closed by Rem0o** 2022-10-26 11:52 UTC

**Comment by ownlyme** [comment] 2022-11-06 18:30
i also noticed that hysteresis works kinda weirdly.
you'd expect that any point of the fan curve would need to be undercut by the selected temperature, but it's working more like a "lag" system that ignores the entire graph.
for example after i reached a certain temperature, the card would only cool down to 55° even though my 0rpm mode starts at 57° with those 15° hysteresis

**Comment by ownlyme** [comment] 2022-11-06 18:33
@Rem0o

**Comment by Rem0o** [comment] 2022-11-06 20:42
The hysteresis indeed doesn't care about the graph points, (except the boundaries).  It basically remembers the last temperature at which it changed. Then it will wait, in your case, a + or - difference of 15 deg from that temperature.

Let say  FanControl opens and your GPU is at 47. The first "state" will be at 47.  It will then wait for a temperature at/under 35 or at/over 62 (15 deg delta).  If it then records 66 deg, it will apply the % for the 66 deg point, then the new "state" will be at 66, and the same logic starts again from 66.

**Comment by ownlyme** [comment] 2022-11-06 21:29
@Rem0o 
just noticed that afterburner has the same issue..
is there any trick you could use to work around it?

**Comment by Rem0o** [comment] 2022-11-06 22:00
@ownlyme  work around what? I don't really understand what you want, given you put a 15 deg hysteresis.

**Comment by ownlyme** [comment] 2022-11-06 22:08
the main issue is that it doesn't cool down properly after a gaming session
it's entirely unpredictable how my fans will behave because the peak temperature varies wildly from game to game

**Comment by Rem0o** [comment] 2022-11-06 22:15
> cool down properly after a gaming session

Again, you'll have to be more precise.   Those are all relative terms. 

If you want to do a graph, try something like this:
![image](https://user-images.githubusercontent.com/14118956/200198015-69c4a2a0-28b1-48da-93f7-31ac9dd88db5.png)
If you don't want the fan ramping up and down at all during load, set a flat section a the top end.

But maybe you don't want a graph at all.  Have you tried the "Target" fan curve?  Set the load temp to the minimum value you want your fans to be spinning, and set the idle temp where you want your fans to stop spinning after a gaming session.

**Comment by ownlyme** [comment] 2022-11-07 00:21
seems like the target fan curve might work for my use case, but it would triple the amount of curves i'm using (usual curve + Target for hysteresis + mix)
would it cause issues if i'm using ~30 curves?
maybe an additional "hysteresis mode" that acts like a shifted curve for decreasing fan speeds would be a useful feature

**Comment by Rem0o** [comment] 2022-11-07 00:29
> seems like the target fan curve might work for my use case, but it would triple the amount of curves i'm using (usual curve + Target for hysteresis + mix)

but do you really need that graph part though? From your graph, you go from like 50% to 70%. You could most likely round that to a flat 60% on the target fan curve, and I would bet your temps wouldn't budge by more than a degree.

But why would you need 30 curves?  You can probably refactor it down and simplify it to like 6-10 curves total, assuming all your case fans are similar.

> would it cause issues if i'm using ~30 curves?

The curve logic is very lightweight, so 30 curves is no problem. The UI might get a bit heavy though, but if you leave the UI window closed on the day to day, there should be no issues performance wise.
