### ISSUE TITLE
HWInfo plugin cant load 

### ISSUE THREAD

**Issue by bczegeny** [Rem0o/FanControl.Releases#896] opened 2022-06-25 06:06 UTC
Getting an error saying the plugin can't load. 

I have the latest HWinfo Pro version, the latest HWInfo plugin. 
HWInfo was working correctly.

This is in the Fan Control Log file
```
2022-06-24 11:03:13 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.HWInfo.HWInfoRegistry.UpdateValues(HWInfoPluginSensor[] sensors) in C:\projects\fancontrol-hwinfo\HWInfoRegistry.cs:line 65
   at FanControl.HWInfo.HWInfoPlugin.Update() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 73
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ```

**Comment by Rem0o** [comment] 2022-06-26 15:49
Duplicate of https://github.com/Rem0o/FanControl.HWInfo/issues/21

**Closed by Rem0o** 2022-06-26 15:49 UTC
