### ISSUE TITLE
Nvidia Memory Junction Temp sensor missing from sensors list. 

### ISSUE THREAD

**Issue by MangyDogUK** [Rem0o/FanControl.Releases#757] opened 2022-05-10 13:57 UTC
Id like to add a curve based on memory junction temps as they can quickly outstrip the GPU memory, but these are missing in the sensor selection list.

Im aware LHM does aggregate these sensors, could these be added?

**Comment by MangyDogUK** [comment] 2022-05-10 14:00
Both are ticked currently. Will try both

**Comment by MangyDogUK** [comment] 2022-05-10 15:12
Strangely my 3080 isn't showing up at all in the sensor list.

I've had odd issues with the Api myself as I can't seem to find the gpu power wattage in an app I'm making.

**Comment by MaceAus** [comment] 2022-05-10 23:09
Hi Rem0o,

I have this same issue with my MSI 2070 Super Ventus. If I remove NvAPI I get no GPU sensor.

I believe that my card should read GPU Hotspot with LHM (AIDA64 reads this correctly) but I get the same results as Mangy.

It seems more like an issue with LHM than FanControl?

Hopefully this information helps. 
It may be irrelevant but Motherboard is:
MSI MPG Z390 Gaming Edge AC

**Comment by Rem0o** [comment] 2022-05-12 01:57
@MaceAus  Make sure you got the LHM GPU enabled. That's what I got.  

If nothing shows up, well, try and dive in there: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

![image](https://user-images.githubusercontent.com/14118956/167976468-76787b65-0712-4b9c-9e21-2207ec96480c.png)
![image](https://user-images.githubusercontent.com/14118956/167976531-f542eb0f-36d0-4446-aaae-9934b1471567.png)

**Comment by MaceAus** [comment] 2022-05-12 06:38
Hi Rem0o,

I just tested this again using the config in your image, but no GPU sensors show up. I just assume it's a LHM issue. Not a big deal, just wanted to note the similarity to Mangy's issue.

Thanks

**Comment by Rem0o** [comment] 2022-05-17 17:24
A lot of people use https://github.com/Rem0o/FanControl.HWInfo to get mem junction compatibility. Otherwise, not much I can do for now. Closing.

**Closed as completed by Rem0o** 2022-05-17 17:24 UTC

**Comment by d-e-n-n-i-s-t** [comment] 2025-03-27 04:20
> ![image](https://user-images.githubusercontent.com/14118956/167646490-0d18cc7e-8403-4395-ad0f-48daa7544f31.png)

Thats why maybe the UI should reflect that only one of LHM/NvApi is active for your GPU (gray out the one not selected?)

> A lot of people use https://github.com/Rem0o/FanControl.HWInfo to get mem junction compatibility. Otherwise, not much I can do for now. Closing.

Isn't it pretty easy to implement junction/hotspot temps natively in NvApiWrapper? I think it would be way easier if a user could just check one box and be done. Currently, to get junction/hotspot temps without LHM, you have to use a plugin (NvThermalSensors), which is a .dll, which sometimes is blocked by the OS at first, which you have to manually install and update, etc etc etc

TimSirmovics, the person that wrote the plugin, also wrote [junction/hotspot support](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/583) for LibreHardwareMonitor. He also linked to a  [frametime capture tool](https://github.com/CXWorld/CapFrameX/commit/dcff36013b73e727845d7b3016e7efd7d46be1e7#diff-b396b43bc1c5bb138acfb1aa4801a0a0e080cf0dcaa203d450fa065126287c12L349-R660) with this feature.
Seems to me like it's only 20 lines of code, is it just an adjustment to the api-request?

**Comment by d-e-n-n-i-s-t** [comment] 2025-03-27 04:21
> ![image](https://user-images.githubusercontent.com/14118956/167646490-0d18cc7e-8403-4395-ad0f-48daa7544f31.png)

Thats why maybe the UI should reflect that only one of LHM/NvApi is active for your GPU (gray out the one not selected?)

> A lot of people use https://github.com/Rem0o/FanControl.HWInfo to get mem junction compatibility. Otherwise, not much I can do for now. Closing.

Isn't it pretty easy to implement junction/hotspot temps natively in NvApiWrapper? I think it would be way easier if a user could just check one box and be done. Currently, to get junction/hotspot temps without LHM, you have to use a plugin (NvThermalSensors), which is a .dll, which sometimes is blocked by the OS at first, which you have to manually install and update, etc etc etc

TimSirmovics, the person that wrote the plugin, also wrote [junction/hotspot support](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/583) for LibreHardwareMonitor. He also linked to a  [frametime capture tool](https://github.com/CXWorld/CapFrameX/commit/dcff36013b73e727845d7b3016e7efd7d46be1e7#diff-b396b43bc1c5bb138acfb1aa4801a0a0e080cf0dcaa203d450fa065126287c12L349-R660) with this feature.
Seems to me like it's only 20 lines of code, is it just an adjustment to the api-request? @Rem0o

**Comment by d-e-n-n-i-s-t** [comment] 2025-03-27 04:22
> ![image](https://user-images.githubusercontent.com/14118956/167646490-0d18cc7e-8403-4395-ad0f-48daa7544f31.png)

Thats why maybe the UI should reflect that only one of LHM/NvApi can be active for your GPU (gray out the one not selected?)

> A lot of people use https://github.com/Rem0o/FanControl.HWInfo to get mem junction compatibility. Otherwise, not much I can do for now. Closing.

Isn't it pretty easy to implement junction/hotspot temps natively in NvApiWrapper? I think it would be way easier if a user could just check one box and be done. Currently, to get junction/hotspot temps without LHM, you have to use a plugin (NvThermalSensors), which is a .dll, which sometimes is blocked by the OS at first, which you have to manually install and update, etc etc etc

TimSirmovics, the person that wrote the plugin, also wrote [junction/hotspot support](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/583) for LibreHardwareMonitor. He also linked to a  [frametime capture tool](https://github.com/CXWorld/CapFrameX/commit/dcff36013b73e727845d7b3016e7efd7d46be1e7#diff-b396b43bc1c5bb138acfb1aa4801a0a0e080cf0dcaa203d450fa065126287c12L349-R660) with this feature.
Seems to me like it's only 20 lines of code, is it just an adjustment to the api-request? @Rem0o

**Comment by Rem0o** [comment] 2025-03-27 14:28
> TimSirmovics, the person that wrote the plugin, also wrote https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/583 for LibreHardwareMonitor. He also linked to a [frametime capture tool](https://github.com/CXWorld/CapFrameX/commit/dcff36013b73e727845d7b3016e7efd7d46be1e7#diff-b396b43bc1c5bb138acfb1aa4801a0a0e080cf0dcaa203d450fa065126287c12L349-R660) with this feature.
Seems to me like it's only 20 lines of code, is it just an adjustment to the api-request? @Rem0o

Yes it could be added, the issue is that NvApiWrapper is dead and not maintained anymore.  The LHM implementation is complete enough though if you want these features.

The tricky thing with the LHM GPU section is that it does both Nvidia and AMD. You might use NvAPIWrapper for an nvidia gpu and the lhm gpu implementation for an AMD gpu or vice-versa.

**Comment by d-e-n-n-i-s-t** [comment] 2025-03-27 15:13
> The tricky thing with the LHM GPU section is that it does both Nvidia and AMD. You might use NvAPIWrapper for an nvidia gpu and the lhm gpu implementation for an AMD gpu or vice-versa.

ahh ok, that makes sense

> Yes it could be added, the issue is that NvApiWrapper is dead and not maintained anymore.

If NvApiWrapper is dead, whats gonna replace it? Only LHM?

**Comment by F3NN3X** [comment] 2025-04-01 22:09
LHM is reporting that the memory junction temperature on my msi 5090 is 255* ... seems a bit high ;) 
so wondering if there is something to do about that? regular temp and hotspot is correct, but no the mem temp

**Comment by d-e-n-n-i-s-t** [comment] 2025-04-01 22:29
@F3NN3X are you using LHM or NvApiWrapper with the plugin?
If it's the plugin, are you using the latest version (1.2)?

**Comment by F3NN3X** [comment] 2025-04-01 22:36
> [@F3NN3X](https://github.com/F3NN3X) are you using LHM or NvApiWrapper with the plugin? If it's the plugin, are you using the latest version (1.2)?

oh man, never mind... i got my tabs confused :P sorry about that.
thought i was commenting on the LHM github, using the latest release of LHM and memory junction temp is reported at 255* but cant find any info about it. 
but i might actually try it out now and see what the temp is reporting

**Comment by d-e-n-n-i-s-t** [comment] 2025-04-02 15:40
@F3NN3X does the problem also occur if you install the "NvThermalSensors"-plugin for FanControl? Using NvApiWrapper
