### ISSUE TITLE
Rx 580 2048sp fan control completely disappeared

### ISSUE THREAD

**Issue by VantsPants09** [Rem0o/FanControl.Releases#2512] opened 2024-05-15 10:47 UTC
My gpu fans don't even show up on the dashboard anymore. It was working with last update. Pls help because ur software is amazing and i need it!!!
Thanks

**Comment by Rem0o** [comment] 2024-05-15 15:58
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/2509

**Closed by Rem0o** 2024-05-15 15:58 UTC
