### ISSUE TITLE
Start with Windows

### ISSUE THREAD

**Issue by miau33** [Rem0o/FanControl.Releases#1051] opened 2022-08-26 17:47 UTC
Hi,

The software dosent start with windows , the box is checked but is not starting with windows..

![image](https://user-images.githubusercontent.com/70064030/186962599-2a76137b-d77a-4197-b436-6a439c8c656d.png)

**Comment by Rem0o** [comment] 2022-08-26 17:58
Try and increase the delay.

Else look at the task in Task Scheduler, and see what's the last run result is:
![image](https://user-images.githubusercontent.com/14118956/186964328-c66e6516-afa4-4219-bba4-2fa0e603bbd7.png)


Also, with FanControl off, try and manually start the task.

**Comment by conebabz** [comment] 2022-08-27 11:21
I am also having some trouble with the start up.. Im not sure what the issue is related too, but sometimes it opens up just fine, and others it opens up in taskmanager, and i can see it's "running".. I can't see it in the process tab, and i can't close it either, just says access denied.. I have been using HWinfo64 also on startup and running fine.. I have disabled the startup to see if that would help.. It doesen't.. Idk how i would increase the delay when i can't access the program as it is right now.. If i try and open the software through explorer, it just opens another in taskmanager, but nothing more happens.. 

I can see in taskscheduler it has run the program and it appears to work properly, only i cannot see it or access it.. 

Idk if this has anything to do with it, but i sometimes experience issues with HWinfo aswell as it freezes and i again can't close it in taskmanager.. I have to reboot my pc if i wanna have any chance of getting it to run again.. As for FanControl..

Otherwise im super happy with the software, i saw Jayz video, and i had prior to that just thought to my self how nice it would be if something like that existed.. So cadeu to you :) 

I have been reading other issues and comments, but i can't seem to find a solution through that.. If you need any log's or anything, pls let me know.. Thanks in advance!

**Comment by Rem0o** [comment] 2022-09-03 21:04
@conebabz  make sure the task in task scheduler is assigned to a "real" user with admin rights. If it's a "SYSTEM" kind of user, you'll get no UI.

**Comment by conebabz** [comment] 2022-09-03 21:30
> @conebabz make sure the task in task scheduler is assigned to a "real" user with admin rights. If it's a "SYSTEM" kind of user, you'll get no UI.

I'm sorry i didnt write it in here, but I got tired of some other stuff around w11, so i went back to win10.. After that i saw somewhere that it's not "supported" for win11.. And ever since i went back to win10 i have not had a single issue with it.. So i guess it was just a win11 issue.. But thank you for your time, and again im very grateful for your software, it's something i have been looking for before..

**Closed** 2022-09-18 18:19 UTC
