### ISSUE TITLE
V166 unknown error on sttartup

### ISSUE THREAD

**Issue by scepterus** [Rem0o/FanControl.Releases#1979] opened 2023-08-15 02:57 UTC
**Describe the bug**
Whenever I start my computer I get an error I've added the lines from the logs.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
```
15/08/2023 05:52:19: System.InvalidOperationException: Cannot set ShutdownMode when application is shutting down or already shut down.
   at System.Windows.Application.set_ShutdownMode(ShutdownMode value)
   at FanControl.App.OnStartup(StartupEventArgs eventArgs)
```

**Relevant hardware specs and setup**
Ryzen 5800x Geforce 1060

**Comment by keywal** [comment] 2023-08-15 11:44
Also having this problem - Started today

**Comment by morgenrot68** [comment] 2023-08-15 12:25
similar error with me. if I want to change the profile via desktoplink, I get this error in the log and an error message pops up since 1.66:
`
15.08.2023 13:41:11: System.InvalidOperationException: "ShutdownMode" kann nicht festgelegt werden, wenn die Anwendung heruntergefahren wird oder bereits heruntergefahren wurde.
   bei System.Windows.Application.set_ShutdownMode(ShutdownMode value)
   bei FanControl.App.<OnStartup>d__12.MoveNext()`

but the profile is changed properly, only this annoying error message always pops up.

when i type this commando in the dos window, i get the error when fancontrol is already running minimized.

`FanControl.exe -c Fullspeed.json`

I think the problem is that the -c cmd command doesn't work anymore if fancontrol has already been started. In the previous versions it worked.

**Comment by scepterus** [comment] 2023-08-15 17:51
![image](https://github.com/Rem0o/FanControl.Releases/assets/56637330/37f09788-e798-4f6d-9960-ad43f8b1744c)
that's the screenshot of it, it still works after that, it does not crash, but it reports that error on start.

**Comment by Rem0o** [comment] 2023-08-16 00:54
Should be fixed in V167

**Comment by scepterus** [comment] 2023-08-16 04:53
Can confirm, updated and did not get this error, great job as always.

**Closed** 2023-08-16 11:46 UTC
