### ISSUE TITLE
FanControl.deps.json and FanControl.runtimeconfig.json showing in tray icon under Configurations

### ISSUE THREAD

**Issue by disaster-chief** [Rem0o/FanControl.Releases#1308] opened 2022-11-20 23:29 UTC
FanControl.deps.json and FanControl.runtimeconfig.json are showing in the tray icon under Configurations. I opened them in notepad, they are very different to my actual config .json files

There are log files only from october.

Not sure if I need to provide a .txt file for hardware specs?

**Comment by Rem0o** [comment] 2022-11-20 23:52
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/1168

**Closed by Rem0o** 2022-11-20 23:52 UTC
