### ISSUE TITLE
Detects cpu/chassis fans only if CPUID HWMonitor is running.

### ISSUE THREAD

**Issue by gustavomgama** [Rem0o/FanControl.Releases#1943] opened 2023-07-25 01:11 UTC
I tested with a fresh config file and it is 100% because of the hwmonitor running. 
MOBO:
EX-A320M-GAMING

**Comment by gustavomgama** [comment] 2023-07-25 01:11
No plugins installed also, fresh download and userconfig file.

**Comment by Rem0o** [comment] 2023-08-01 15:34
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/1171

**Closed by Rem0o** 2023-08-01 15:34 UTC
