### ISSUE TITLE
Missing speed sensors

### ISSUE THREAD

**Issue by lucenli** [Rem0o/FanControl.Releases#191] opened 2021-03-22 10:13 UTC
![image](https://user-images.githubusercontent.com/16946496/111973666-b28e5080-8b39-11eb-9638-09c86c66440c.png)

Hi Rem0o, I'm having this error pops up every time I restart my PC and open FanContorl. Once click OK it will refresh and everthing seems ok then.
It is just really anoying because I don't know why I am getting this error, would you please help me with it?

Thx!

the Fan control version is ver71.
Win 10 20H2
Mother board is MSI B550 Unify-x
and I also have Corsiar iCue installed.

Does that make any sense to anyone please?

**Comment by Rem0o** [comment] 2021-03-22 13:47
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/187

**Closed by Rem0o** 2021-03-22 13:47 UTC
