### ISSUE TITLE
Frequent errors requiring sensor refresh

### ISSUE THREAD

**Issue by trowieuk** [Rem0o/FanControl.Releases#2208] opened 2023-12-23 17:14 UTC
Started on the 20th, either after a fancontrol update or hwinfo update but every few hours it throws errors.

Log attached.

**Comment by Rem0o** [comment] 2023-12-23 18:47
No log attached

**Comment by trowieuk** [comment] 2023-12-24 11:28
[log_1.txt](https://github.com/Rem0o/FanControl.Releases/files/13761624/log_1.txt)
apologies.

**Comment by Rem0o** [comment] 2023-12-24 15:56
FanControl.HWInfo throws an error because there is a duplicate sensor from HWInfo.

**Comment by trowieuk** [comment] 2023-12-24 15:59
> FanControl.HWInfo throws an error because there is a duplicate sensor from HWInfo.

anyway to see which one? I haven't changed anything in HWInfo just did the last update...

**Comment by DfrostX** [comment] 2023-12-24 16:02
“HWInfo sensor failed momentarily during operation: HWInfo/DDR5 DIMM [#1] (BANK 0/Controller0-ChannelA-DIMM1)/SPD Hub Temperature/°C – Missing”

Basically, FanControl is not receiving any data from your RAM temperature sensor for a longer than expected period, at which point it’s Hwinfo plugin consider it not missing and report the sensor a such to FanControl.

You could add an alarm to that sensor in HWinfo to validate this theory (also, the sensor should go grey when this happen, this is how HWinfo handles "gone missing" sensors). The root cause could be either a bug in HWinfo (doubtful), a collision with another monitoring or RGB software or an unreliable physical sensor on the RAM stick that goes on and off. There are multiple threads on HWinfo forum about this type of issue [Exemple](https://www.hwinfo.com/forum/threads/ram-detection-lost-occasionally.8657/)

**Comment by DfrostX** [comment] 2023-12-24 16:04
I think its failing to report.

Any RGB software running? https://www.hwinfo.com/forum/threads/ram-detection-lost-occasionally.8657/

**Comment by trowieuk** [comment] 2023-12-24 23:30
> I think its failing to report.
> 
> Any RGB software running? https://www.hwinfo.com/forum/threads/ram-detection-lost-occasionally.8657/

No RGB software other than ones bundled with it but turned off, razer and icue for example.

**Comment by marceloavf** [comment] 2023-12-28 03:49
Happens to me too everytime it startup with windows, even increasing the delay at user logon
[log_1.txt](https://github.com/Rem0o/FanControl.Releases/files/13783120/log_1.txt)

**Comment by ronny130286** [comment] 2023-12-29 18:17
I have the same "issus", after xx minute i get the messager that der HwInfo senosr are missing, if i use ctrl+r  to refresh the data. the sensor data are avalible, but fev minutes later the same issus are back.

I have try it with different hwinfo version, without success.
My log:

```
29.12.2023 19:02:10: HWInfo sensor failed momentarily during operation: HWInfo/DDR5 DIMM [#1] (BANK 0/Controller0-DIMM1)/SPD Hub Temperatur/°C - Missing
29.12.2023 19:02:10: Unhandled exception in FanControl v175.0.0.0
29.12.2023 19:02:10: System.Exception: HWInfo sensors failed: HWInfo/DDR5 DIMM [#1] (BANK 0/Controller0-DIMM1)/SPD Hub Temperatur/°C
   at FanControl.HWInfo.HWInfoPlugin.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update() in C:\Users\Remi\source\repos\FanControl\FanControl.Library\Domain\BackendProviders\Plugin\PluginBackendProvider.cs:line 71
   at FanControl.Domain.ComputerAccessLayer.Update() in C:\Users\Remi\source\repos\FanControl\FanControl.Library\Domain\ComputerAccessLayer.cs:line 221
   at FanControl.Domain.ApplicationClock.DoActions() in C:\Users\Remi\source\repos\FanControl\FanControl.Library\Domain\ApplicationClock.cs:line 66
--- End of stack trace from previous locaation ---
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by DfrostX** [comment] 2023-12-31 13:50
Ok I think I found the issue, since I just had the same happen to me during an OCCT memory test. 

To compensate for a sensor flaw of DDR5, Martin of HWinfo64 removed some temparatur values from being reported (see [here for details](https://www.hwinfo.com/forum/threads/ddr5-spd-hub-temperature-occasionally-spiking.8976/post-42870) ). This change was added to 4.68, so indeed rolling back to a  previous buil will fix the issue. The problem with this is that you will now be stuck on that build until something gets fixed

In a nutshell, once your DIMM hit 47.75c, the sensor will go grey in HWinfo64, which means it is now "dormant". This create a situation where it will not report to the FanControl HWinfoplugin until either the temp of the DIMM go over or under 47.75c again... Which can take more time than the timeout of the plugin. Thus, the error you are getting.

No clue how this can be fixed from a FanControl/ HWinfoplugin standpoint. Someone should report it to Martin of HWinfo64 and see what he can do.

@Rem0o , I thought when a sensor goes missing in HWinfo64plugin, that it would keep the last know value instead of reporting an error. I guess there is still a timeout period before you consider the sensor disabled.

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/13801316/log.txt)

**Comment by Fr0stX76** [comment] 2023-12-31 14:04
Nevermind, I found this on the plugin history "After 10 consecutive update with a missing sensor, it will throw as it did before"

I think the updates are of 1hz (1000ms), so I would assume if the sensor stopped reporting for over 10 seconds, it is considered disabled for FanControl and the error will pop-up

**Comment by trowieuk** [comment] 2023-12-31 14:12
I have disabled hwinfo plugin and still getting hwinfo errors. also lianli plugin errors.
new log attatched.
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/13801394/log.txt)

**Comment by Fr0stX76** [comment] 2023-12-31 14:47
If your curves are based on hwinfoplugin sensors and you disable the plugin... Its expected you will have errors. Remove any curve based on a hwinfo sensor, close FanControl then delete the plugin dll. This should remove hwinfo errors.

As for the LianLi plugin, I don't use it, so can't say.

**Comment by marceloavf** [comment] 2023-12-31 16:46
> Ok I think I found the issue, since I just had the same happen to me during an OCCT memory test.
> 
> To compensate for a sensor flaw of DDR5, Martin of HWinfo64 removed some temparatur values from being reported (see [here for details](https://www.hwinfo.com/forum/threads/ddr5-spd-hub-temperature-occasionally-spiking.8976/post-42870) ). This change was added to 4.68, so indeed rolling back to a previous buil will fix the issue. The problem with this is that you will now be stuck on that build until something gets fixed
> 
> In a nutshell, once your DIMM hit 47.75c, the sensor will go grey in HWinfo64, which means it is now "dormant". This create a situation where it will not report to the FanControl HWinfoplugin until either the temp of the DIMM go over or under 47.75c again... Which can take more time than the timeout of the plugin. Thus, the error you are getting.
> 
> No clue how this can be fixed from a FanControl/ HWinfoplugin standpoint. Someone should report it to Martin of HWinfo64 and see what he can do.
> 
> @Rem0o , I thought when a sensor goes missing in HWinfo64plugin, that it would keep the last know value instead of reporting an error. I guess there is still a timeout period before you consider the sensor disabled.
> 
> [log.txt](https://github.com/Rem0o/FanControl.Releases/files/13801316/log.txt)

Nice found, I was seing that my PCH fan speed and sensor also are unrechable when stating, but even putting like a 2min delay for FanControl, it still happens.

**Comment by Fr0stX76** [comment] 2023-12-31 17:32
@marceloavf I don't think adding a delay will solve anything. 

The issue is in the lack of data being sent by Hwinfo for longer than allowed by the plugin HWinfo. I know why for the DDR5 memory (I was the one who pointed the fluke to Martin on HWinfo forum), but for your chipset (PCH) it is not directly related to this change. But I would think it is something similar, as in the PCH sensors go down for longer than expected by the plugin.

**Comment by Rem0o** [comment] 2023-12-31 17:59
> @Rem0o , I thought when a sensor goes missing in HWinfo64plugin, that it would keep the last know value instead of reporting an error. I guess there is still a timeout period before you consider the sensor disabled.

Well after how long should it be considered a problem? 30 seconds? 60 seconds? 1 hour? The value is written in the Windows registry by HWInfo. The plugin will report a problem if the value in the registry is missing, as if HWInfo was closed or was no longer reporting that value at all, at which point whatever the last value was is not relevant/reliable.

**Comment by Fr0stX76** [comment] 2023-12-31 18:44
@Rem0o, I'm not sure what to answer. My first thought is : Do you need a timeout at all once initial value has been received? 

Past that, if the sensor goes dark, then reusing the last know value would be fine until the sensor comes back online (if). The system safety argument cannot be used since when this timeout happens, all fans either stop or go to minimum speed, which is arguably worst.

In the meantime, I just wrote to Martin to see if something can be done on the HWinfo side.

**Comment by Fr0stX76** [comment] 2024-01-02 16:44
Ok update on this, I just found a workaround but it does involve a but of work.

I created a custom sensor based on my RAM sensor (See [here](https://www.hwinfo.com/forum/threads/custom-user-sensors-in-hwinfo.5817/) for how to create one):

> Windows Registry Editor Version 5.00
[HKEY_CURRENT_USER\SOFTWARE\HWiNFO64\Sensors\Custom\PCXXX\Temp1]
"Name"="DIMM1 "
"Value"="\"DIMM1 Temp\""

I then changed HWinfo gadget to report the custom sensor instead of the one from the DIMM (So only the custom one gets reported). This popped and error in FanControl but it was expected as I now had a new sensor (while the older one was deleted). I just added the new sensor to all associated graphs and stuff.

This fixed the sensor going offline issue. Of course if the original sensor my custom one ius based on is missing when I start HWinfo, I will get an error message... But this is normal behavior.

**Comment by Fr0stX76** [comment] 2024-01-12 00:41
Update on this, HWiNFO v7.69 Beta 5330 now does not delete the registry lines needed by the plugin, even when the sensor stop reporting. Instead the last know value keeps being reported. This should fix a lot of issues people had with the plugin., especiallly with slow to report sensors.

Obviously this will not fix any issue were the sensor is not detected upon launching HWinfo.

**Comment by Rem0o** [comment] 2024-01-17 22:17
Can I close this? @Fr0stX76 @trowieuk

**Comment by Fr0stX76** [comment] 2024-01-18 01:43
@Rem0o as far as I'm concerned, yes. HWiNFO v7.69 Beta 5330 resolved all issues associated to loss of data sent by one of it's sensor.

**Closed** 2024-01-18 13:11 UTC
