### ISSUE TITLE
Missing sensors after latest Windows 11 update (KB5039212)

### ISSUE THREAD

**Issue by mejico** [Rem0o/FanControl.Releases#2575] opened 2024-06-14 21:46 UTC
When My system booted up this morning fan control started but is missing most of the sensors that were previously available.  It is also reporting CPU (5800x) at 192C.  Doesn't control any of the case fans as they don't appear.  The only thing it finds properly is the RTX 3080.  The only change that has occurred is that windows installed update KB5039212 overnight (i.e. after restarting).

The fault symptoms are almost identical to those reported in bug issue #2571 but closing Kaspersky doesn't do anything and Kaspersky hasn't change prior to the bug appearing.

**Comment by Rem0o** [comment] 2024-06-14 22:30
Well the fact you got Kapersky, the exact same symptoms, and to date nobody without Kapersky has the problem, I would bet it is related. I don't know Kapersky at all but it seems like uninstalling fixed it, disabling might not be enough.

**Comment by mejico** [comment] 2024-06-14 22:33
Th only reason I suspect the windows update is that is the only change that occurred prior to the fault.

**Comment by Rem0o** [comment] 2024-06-14 22:37
Well if it was the Windows update, everybody with said update would get the same problem, but it doesn't appear so.

**Comment by SirStew** [comment] 2024-06-15 01:11
@mejico I made a thread recently about this, I bet you it is Kaspersky, about 3 of us so far have uninstalled and the fans and sensors all came back, try uninstalling or try https://github.com/Rem0o/FanControl.Releases/issues/2563 looking there for a fix someone says is working with Kaspersky installed, didnt work for me but best worth a try if you want Kaspersky still.

**Comment by pcooke9** [comment] 2024-06-15 03:19
No problems for me with KB5039212 or Kaspersky on my system-

https://github.com/Rem0o/FanControl.Releases/issues/2571#issuecomment-2169073942

**Comment by Leo-55ru** [comment] 2024-06-15 10:08
With FanControl turned on and fully configured, when you open any monitoring program FanControl loses all fans and sensors completely. 
Tested personally with Aida64, Gpu-z, Cpu-z, Rivatuner, HWiNFO64. 
I repeat opening any monitoring program breaks FanControl.
Pardon my English. I translated the text in DEEPL.

**Comment by pcooke9** [comment] 2024-06-15 11:48
> With FanControl turned on and fully configured, when you open any monitoring program FanControl loses all fans and sensors completely. Tested personally with Aida64, Gpu-z, Cpu-z, Rivatuner, HWiNFO64. I repeat opening any monitoring program breaks FanControl. Only a complete reboot of the PC helps. Any ideas how to fix FanControl? V193
> 

I'm not having any trouble running Aida64, CPU-Z, GPU-Z, Afterburner, or HWiNFO64 with Fan Control at the moment. That isn't something I'd normally do at all BTW. Just figured I'd try running them temporarily to help you confirm, but it's all good here.

Simultaneously running multiple apps that monitor or control hardware is generally a bad idea, even if you don't normally have any issues doing so. Sometimes the different apps end up trying to juggle the hardware polling back & forth which can throw sensors out of whack.

**Comment by Leo-55ru** [comment] 2024-06-15 12:05
The point is, it started just a couple days ago.
All of the above software has never conflicted with FanControl, even if you run them all at once.
I've never had this problem before. 
I have never had such a conflict of applications.
I don't know what the cause of this behavior is.
Of the latest software updates was FanControl on V193 and the windows 10 update for June 2024.
Rolling back the latest windows 10 update does not solve the problem.
Rolling back the FanControl update to V192 does not solve the problem.
I don't know where to find the problem!

**Comment by Leo-55ru** [comment] 2024-06-15 12:47
![2024-06-15 184455](https://github.com/Rem0o/FanControl.Releases/assets/172894201/764e1bec-a4f3-409e-8c29-da63b2d53b56)

**Comment by Rem0o** [comment] 2024-06-15 16:34
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/2563#issuecomment-2170217932

**Closed by Rem0o** 2024-06-15 16:34 UTC
