### ISSUE TITLE
Avast blocking fancontrol.sys driver

### ISSUE THREAD

**Issue by xeophyte** [Rem0o/FanControl.Releases#1698] opened 2023-04-04 18:53 UTC
Avast Free Antivirus after updating to version 23.3.6058 is blocking fancontrol.sys driver and the Fan Control cannot be started.

![AvastUI - 2023 04 04_20 23 31](https://user-images.githubusercontent.com/121556803/229890812-0d5f7dcc-4b5e-4ac1-a320-a7af8972bcdc.png)
Adding the program/sys file to the avast exceptions does nothing.
I have to disable this option completely for the program to run:

![2023-04-04_20-27-47](https://user-images.githubusercontent.com/121556803/229891220-d2307745-b997-4a19-b235-0a2d2e6ed543.png)
but it has to be disabled all the time and then of course security decreases.

Fan Control v153

**Comment by Rem0o** [comment] 2023-04-05 01:18
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/1521.

**Closed by Rem0o** 2023-04-05 01:18 UTC
