### ISSUE TITLE
FEATURE Request

### ISSUE THREAD

**Issue by Mettkrieger** [Rem0o/FanControl.Releases#60] opened 2020-10-30 18:29 UTC
Hey,

could you maybe integrate this: https://github.com/jonasmalacofilho/liquidctl to be able to set fan curves based on liquid temperature of some AiO coolers (If that's even possible)? Maybe even adjusting pump speed through the UI.

Would be greatly appreciated :)

**Comment by Rem0o** [comment] 2020-10-30 18:32
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/42

**Closed by Rem0o** 2020-10-30 18:32 UTC
