### ISSUE TITLE
Fan control suddenly fails to correctly read AMD GPU temperatures from sources

### ISSUE THREAD

**Issue by NoFailer** [Rem0o/FanControl.Releases#2507] opened 2024-05-13 08:32 UTC
**Describe the bug**
Fan control suddenly shows very high/incorrect temperature numbers for my AMD GPU which causes the program to set my fans to 100%. The only source that is currently working normally is the GPU core. Other programs like OCCT show all temperatures/sources just fine.

![image](https://github.com/Rem0o/FanControl.Releases/assets/53854947/77ead274-4c58-466d-86d6-5c875c6239ec)

![image](https://github.com/Rem0o/FanControl.Releases/assets/53854947/bf4b8064-b5a5-45e9-b274-d137a3eb6044)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No logs.

**Relevant hardware specs and setup**
- Fan Control V189
- RX 6900 XT

**Comment by NoFailer** [comment] 2024-05-13 08:35
If there is anything else I can do, let me know. I will try to get back to you as soon as I can.

**Comment by Rem0o** [comment] 2024-05-13 13:36
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/2465

**Comment by Rem0o** [comment] 2024-05-13 13:37
In the meantime, I recommend using this https://github.com/Rem0o/FanControl.ADLX instead of the GPU section of LHM in sensor settings.

**Closed by Rem0o** 2024-05-13 13:36 UTC
