### ISSUE TITLE
Feature request: Automatically switch configs when certain apps are running

### ISSUE THREAD

**Issue by Torbins** [Rem0o/FanControl.Releases#2664] opened 2024-08-16 16:12 UTC
Sometimes it is easier to change fan speeds based on currently running executable. So that when you start a game, app will automatically switch to a different config. Please, implement some ability to automatically switch configs, based on running apps.

**Comment by Rem0o** [comment] 2024-08-17 17:26
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/2478

**Closed by Rem0o** 2024-08-17 17:26 UTC
