### ISSUE TITLE
[BUG] Control card does not pick speed from corresponding curve

### ISSUE THREAD

**Issue by ddenev** [Rem0o/FanControl.Releases#85] opened 2020-12-04 14:50 UTC
When Fan Control starts for the 1st time (e.g. after computer start), very often one of the Control cards for a PWA fan does not pick up its speed from the corresponding curve configuration. See the screenshot below:
![image](https://user-images.githubusercontent.com/1393766/101177318-5964e480-3650-11eb-948c-f4b512d207b1.png)

The "Bottom" control stays at 0% (RPM is greater than 0 since this is a non-stoppable PWA fan) although the corresponding curve is set to 28%.

The only way to fix this is to disable/enable the Control but this is annoying to do every time.

Here is how it looks after applying the above fix:
![image](https://user-images.githubusercontent.com/1393766/101177665-bfea0280-3650-11eb-824d-f8950da0fc37.png)

**Comment by Rem0o** [comment] 2020-12-04 15:52
I was able to reproduce the problem by copying this exact state, however I'm not sure how your control gets to 0%, since your curve returns 28. I made a fix, will be in the next version.

**Comment by Rem0o** [comment] 2020-12-04 20:48
Fixed in https://github.com/Rem0o/FanControl.Releases/releases/tag/V59

**Closed by Rem0o** 2020-12-04 20:48 UTC
