### ISSUE TITLE
Errors while restoring config, missing sensors

### ISSUE THREAD

**Issue by NCHlab** [Rem0o/FanControl.Releases#81] opened 2020-11-26 00:24 UTC
Whenever I start my pc for the day and FC auto starts up I get this error:

![image](https://user-images.githubusercontent.com/32630046/100294083-9dcff080-2f7d-11eb-9ded-b377ac4015c8.png)

And my controls are missing (only gpu shows). 

I have to exit FC and start again in order for it to be able to load the data properly and gain access to the other panels

**Comment by Rem0o** [comment] 2020-11-26 00:45
Does it tries to refresh after the popup closed when this occurs? Also does it happens everytime?

**Comment by NCHlab** [comment] 2020-11-26 00:48
> 
> 
> Does it tries to refresh after the popup closed when this occurs? Also does it happens everytime?

I do recall seeing a refresh popup sometimes, but it does nothing when I press "yes".

Its been happening everytime for the past week.

I have to exit the program and start up as admin (unsure if it has same issues without elevated perms).

**Comment by Rem0o** [comment] 2020-11-26 00:50
Well the program does requires admin. So if for some reason it starts without admin rights, it won't detect anything as you see here.

**Comment by NCHlab** [comment] 2020-11-26 00:51
> 
> 
> Well the program does requires admin. So if for some reason it starts without admin rights, it won't detect anything as you see here.

I have ensured that it runs with elevated perms in the task scheduler

**Comment by Rem0o** [comment] 2020-11-26 00:53
If you manually open it without the task scheduler upon boot, is the problem there still?

**Comment by NCHlab** [comment] 2020-11-26 11:49
> 
> 
> If you manually open it without the task scheduler upon boot, is the problem there still?

Disabled FC task on boot (before it started since 30sec delay) and manually opened it and it worked fine

**Comment by Rem0o** [comment] 2020-11-26 15:44
> > If you manually open it without the task scheduler upon boot, is the problem there still?
> 
> Disabled FC task on boot (before it started since 30sec delay) and manually opened it and it worked fine

So the problem is in the way the application is launched from the Task Scheduler.... Is your Windows account admin?

**Comment by Ascen1ty** [comment] 2021-02-07 21:44
I've randomly started getting this issue too, since the latest update?

My issue seems to be a little different though - once closing FanControl after boot, I am unable to re-open it at all: it's there, running in Task Manager, the task icon/gui won't appear until I end the task & delete the file name "CACHE", in the root dir. 

I have temporarily fixed this by:

- Deleting "CACHE"
- Running FanControl.exe
- Loading my saved config
- Exiting FanControl 
- Setting the "CACHE" file as read only

The above has resolved the issue upon boot & I haven't seen it happen again (yet), but I am unsure as to why it started happening. I've tried running FanControl from another directory (currently runs from C:\Program Files) & also downgrading to a previous version, but the issue persists, so this fix will have to do for now.

Hope this helps anyone else who may be having this issue.

**Comment by tadejdanev** [comment] 2021-03-05 17:46
I'm getting same error.

**Comment by Rem0o** [comment] 2021-03-05 18:02
Make sure the program run as admin and that it doesn't start too soon after you logged in.

**Comment by tadejdanev** [comment] 2021-03-07 06:33
> 
> 
> Make sure the program run as admin and that it doesn't start too soon after you logged in.

works :)

**Closed** 2021-03-23 18:28 UTC
