### ISSUE TITLE
Violation of GitHub Sponsors Guidelines

### ISSUE THREAD

**Issue by gh000000st** [Rem0o/FanControl.Releases#2872] opened 2024-12-14 16:27 UTC
It appears that your repository is **displaying the GitHub Sponsors logo and linking to the GitHub Sponsors page**, despite the repository being **closed-source**.

As per GitHub's guidelines for the Sponsors program, **the logo and link should only be used for open-source projects or contributors**. GitHub Sponsors is intended to support **open-source work**, and using the logo or link for closed-source repositories is a violation of these guidelines.

To comply with these rules, please remove the GitHub Sponsors logo and link from your closed-source repository.

**If you contribute to open-source projects**, you **may** still be eligible to use GitHub Sponsors **for those contributions**, provided the link is clearly associated with your open-source work, not your closed-source project.

Thank you for addressing this!

**Comment by Rem0o** [comment] 2024-12-15 18:28
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/2874

**Comment by gh000000st** [comment] 2024-12-19 19:00
Thank you for your response. I appreciate the clarification about how your repository functions as a central hub for various components, including those with open-source contributions.

However, GitHub's Sponsors guidelines emphasize that the program is primarily intended to support open-source work. To avoid ambiguity, it would be helpful to ensure that any usage of the GitHub Sponsors logo or link is explicitly tied to your open-source contributions rather than a closed-source repository.

If you believe your use aligns with the guidelines, clarifying this alignment publicly in your repository (e.g., in your README) might help prevent misunderstandings. While it’s true that GitHub hasn’t intervened or raised concerns so far, adhering to their guidelines proactively can avoid potential issues in the future.

Could you provide further details on how your Sponsors page emphasizes your open-source contributions? That may help in confirming alignment with GitHub's terms.

Thank you again for taking the time to address this matter.

**Comment by Rem0o** [comment] 2024-12-19 19:16
I will take a look at adding a disclaimer in the README specifying the sponsor button "intentions" versus a standard paypal donation for Fancontrol itself. Users may decide to use either at that point depending on their motivations.

**Comment by gh000000st** [comment] 2024-12-19 19:22
Thank you for your thoughtful response and willingness to address this matter transparently by adding a disclaimer in the README. Specifying the intent behind the sponsor button will help ensure clarity for users and demonstrate proactive compliance with GitHub’s guidelines.

If you would like assistance drafting the disclaimer or have questions about how to frame it effectively, feel free to reach out. Additionally, if you’re using open-source components or contributing to open-source libraries, you might want to highlight these efforts on your Sponsors page. This could further align the page with GitHub’s open-source-focused ethos.

Let me know how I can assist further, and thank you for your continued contributions!

**Comment by Rem0o** [comment] 2024-12-19 20:50
I think something like this would be sufficient:

> ## GitHub Sponsors 
>The GitHub Sponsor button on this page is intended for the related open-source work surrounding FanControl. This includes contributions to the open-source libraries used, mainly [LHM](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor), the plugin system and the various open-source plugins I contribute to, the AMD gpu driver support through [ADLXWrapper](https://github.com/Rem0o/ADLXWrapper), and more.  Your sponsorship helps me continue to contribute to the community, maintain existing projects, and develop new ones. It does not apply to the main program (FanControl) itself. Use the [Paypal](https://www.paypal.com/donate/?cmd=_donations&business=N4JPSTUQHRJM8&currency_code=USD&source=url&item_name=Fan+Control) donation button if your intent is to support the FanControl software itself.

**Comment by gh000000st** [comment] 2024-12-19 22:24
I agree; this effectively clarifies how the GitHub Sponsor button relates to your open-source contributions.

Thank you for showcasing how such matters can be raised and addressed constructively.

**Closed** 2024-12-19 22:25 UTC
