### ISSUE TITLE
Debug output spammed by "A snackbar message is waiting..."

### ISSUE THREAD

**Issue by ringoz** [Rem0o/FanControl.Releases#1513] opened 2023-02-07 12:54 UTC
To reproduce the issue, please:

1. Enable "Start with Windows" setting and restart the OS.
2. Wait for FanControl to start, but do not open it from tray.
3. Launch [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview)
4. Observe these messages logged every second:

```
[15776] FanControl.exe Warning: 0 : 
[15776] A snackbar message is waiting, but no snackbar instances are assigned to the message queue. 
[15776] FanControl.exe Warning: 0 : 
[15776] A snackbar message is waiting, but no snackbar instances are assigned to the message queue. 
[15776] FanControl.exe Warning: 0 : 
[15776] A snackbar message is waiting, but no snackbar instances are assigned to the message queue. 
[15776] FanControl.exe Warning: 0 : 
[15776] A snackbar message is waiting, but no snackbar instances are assigned to the message queue. 
[15776] FanControl.exe Warning: 0 : 
[15776] A snackbar message is waiting, but no snackbar instances are assigned to the message queue. 
[15776] FanControl.exe Warning: 0 : 
[15776] A snackbar message is waiting, but no snackbar instances are assigned to the message queue. 
```

**Comment by Rem0o** [comment] 2023-02-07 14:12
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/1457

**Closed by Rem0o** 2023-02-07 14:12 UTC
