### ISSUE TITLE
Since last update: Can't close the program at all and fan speed doesn't apply

### ISSUE THREAD

**Issue by Kenshokram** [Rem0o/FanControl.Releases#1867] opened 2023-06-30 08:31 UTC
**Describe the bug**
<img width="179" alt="image" src="https://github.com/Rem0o/FanControl.Releases/assets/38762239/193e1c22-2509-4206-a124-251c329f5ff3">
The fan speed of 30% doesn't apply to these frontal fans anymore, even when force applying, before the update it did so.

And the more wild issue, I can't close the program. Clicking on the X to close does nothing, clicking on exit in the menu does nothing.

**Relevant hardware specs and setup**
MSI PRO Z690-A WIFI Socket 1700
Intel Core i9-13900K 5.8GHz
Corsair iCUE H170i ELITE CAPELLIX XT
PNY GeForce RTX 4090 VERTO 24GB
Case Lianli Lancool III

**Comment by Kenshokram** [comment] 2023-06-30 08:55
... And now it does, after closing (via task manager) and opening 3 times (I opened it again to try something I read on here) it again lets me close it and it sets that fan speed down to 30.

Not sure anymore of why is what!

**Comment by Kenshokram** [comment] 2023-06-30 12:40
and after an nvidia driver update and a restart, again it doesn't apply the speed to the frontal fans

and now as bonus, the edit button on curves doesn't do anything (still has the "pressed" animation tho)

**Comment by willhenwood** [comment] 2023-06-30 17:20
I'm leaving a comment here as I am having the same issues as the OP.

**Comment by InterClaw** [comment] 2023-06-30 19:58
I'm having these weird problems as well today. Can't close the window. Can't exit via tray menu. Can only minimize to the taskbar.

The main window keeps refreshing several times as well on startup.

Tried going back to V161, but it behaves the same way on that version now, so it's something else.

**Comment by InterClaw** [comment] 2023-06-30 20:06
V160 same problem.

It's also not updating its temp sensors and I can hear the fans starting and stopping on their own. It's basically not working at all now.

**Comment by NorbertJ91** [comment] 2023-07-01 06:10
All has been ok till the last update V162 I believe, 
I've got the same issues as above, fancontrol window won't close either through [X] or right-click on the taskbar.
The values for fan speeds and temps were not refreshing, it's showing I guess whatever it pulled at the second of the start-up. 
Rolled back just-in-case to V159 since above 160 and 161 have been mentioned to be problematic, and V159 works fine. 
specs: Win10, Gigabyte Z490 Vision D,  i7 10700k, RTX3080.

**Comment by jquaglia** [comment] 2023-07-01 06:48
I've been running V157 for the last 3 months and have had no issues until after I updated windows 11 last night. I started it up and my config is there except the case fans aren't anymore. Also not able to close the app or basically do anything in the app. I can go through the menus but none of the options take/do anything. Seems like the latest windows update broke something crucial.

**Comment by ELowry** [comment] 2023-07-01 08:05
Just including that I am experiencing the same issue. The window won't close, and I am pretty certain the fan curves are not getting applied.

I am running Windows 11 build 22621.1928 and Nvidia drivers version 536.40; both came out about the same time as FanControl v162.

**Comment by PatrickScherer** [comment] 2023-07-01 10:03
I'm having the same issue. I can't close the window and the fan speed is not being applied (even with manual control on).
Problem started when I updated to the most recent version. No other changes.
Running Windows 11 Home, build 22621.1848 and Nvidia driver 536.23.

**Comment by InterClaw** [comment] 2023-07-01 14:30
I tried disabling the HWiNFO plugin. Had no effect.
The .NET 4.8 vs. 7.0 versions doesn't seem to matter either.
Both Windows 10 and 11 affected.

**Comment by InterClaw** [comment] 2023-07-01 15:27
I also uninstalled every Windows update it would let me from the past few days, but it didn't help.

**Comment by Rem0o** [comment] 2023-07-01 16:33
Any logs.txt ?   Something is obviously hanging the main thread.

**Comment by PatrickScherer** [comment] 2023-07-01 16:50
> Any logs.txt ? Something is obviously hanging the main thread.

None here

**Comment by Rem0o** [comment] 2023-07-01 16:56
If you can access Sensor settings, try and untick Embedded EC if you got an Asus board, then controllers, then InpOut. See if any of them is responsible.

![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/8377f1e6-6f38-4b62-9b1c-b1a7615dcc77)

**Comment by willhenwood** [comment] 2023-07-01 20:56
I'll attach my log.txt if this is helpful. Temporary solution is to exit and restart the app. Things seem to work fine then.

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/11927111/log.txt)

**Comment by InterClaw** [comment] 2023-07-02 12:16
For me this problem has disappeared (knock on wood) as suddenly as it appeared.

What I did:
1. Since uninstalling the Windows updates didn't help, I let Windows update itself back again. I also went back to Nvidia 536.40.
2. I pulled out the motherboard manufacturer's software "ASRock Phantom Gaming Tuning" (wow, such gaming) to control some of the fans that way, until there would be a solution to this problem. Proceeded to adjust some of the fan speeds to get a decent baseline that is controlled through the BIOS.
3. After a reboot or two (due to the updates), it seemed like FanControl was not only responsive like normal, but it was also setting the fan speeds, overriding the BIOS values as normal!

And now everything is back to normal. I can't explain what fixed it though.

I have an ASRock B550 Phantom Gaming-ITX/ax and the relevant controller on that board is "Nuvoton NCT6792D". I'm running V162 .NET 7.0 now as well.

(It not only is back to normal, it actually works better, since now with the new and more generous BIOS curves the fans are already spinning when starting Windows, so I'm not getting a missing sensor warning that I used to always get before, which wasn't helped by delaying the start. FanControl _itself_ had to be running for a while, starting the fans, before it went away. That's not an issue for me anymore. Should have realized and done this a long time ago! This might have been related to my weird Phanteks T30 fans.)

**Comment by willhenwood** [comment] 2023-07-02 16:49
@Rem0o - I have an Asus motherboard, and did try to disable the embedded EC. Trouble is, accessing the Sensor Settings menu is not possible when FanControl opens when Windows starts. In fact, I can't really access anything except for the menu. This is a phenomenon that I cannot consistently replicates; sometimes I _can_ access the sensor settings and disabling embedded EC once the refresh takes place. 

Restarting FanControl does seem to fix everything though. Not the end of the world, it's just the fans spin a little quicker.

**Comment by vermi5** [comment] 2023-07-04 10:47
Same symptoms as OP here, attaching most recent log

nvidia drivers 531.79

In one of the instances I had an error msg onscreen about nvapi needing to be restarted. That one time, I was able to finish fancontrol process from taskmanager and it ran normally at next launch.

[log_1.txt](https://github.com/Rem0o/FanControl.Releases/files/11948504/log_1.txt)

**Comment by InterClaw** [comment] 2023-07-04 12:34
Maybe you guys should try uninstalling and reinstalling some of the latest .NET updates. Perhaps they were not deployed properly before, but now are? Just a theory.

**Comment by willhenwood** [comment] 2023-07-04 13:03
> Maybe you guys should try uninstalling and reinstalling some of the latest .NET updates. Perhaps they were not deployed properly before, but now are? Just a theory.

I had a little time to address this theory. The latest .NET is 4.8.1. Tried uninstall/reinstall, but no difference :(
Thank you for suggesting, however :)

**Comment by willhenwood** [comment] 2023-07-07 11:15
OK I think I might have found what was causing this issue.

Since updating to v162, if you enable FanControl to start minimised before updating, it will no longer do so. Just go to the settings, check that the tickbox is indeed ticked. I think this might be down to the .json file having a discrepancy but I'm not well versed enough in coding to say whether this was a definitive answer.

This seemed to have worked for me. Every startup in the last 72 hours has enabled FanControl to start minimised and all fans follow their profile. Hope this helps.

**Comment by vermi5** [comment] 2023-07-07 12:32
> OK I think I might have found what was causing this issue.
> 
> Since updating to v162, if you enable FanControl to start minimised before updating, it will no longer do so. Just go to the settings, check that the tickbox is indeed ticked. I think this might be down to the .json file having a discrepancy but I'm not well versed enough in coding to say whether this was a definitive answer.
> 
> This seemed to have worked for me. Every startup in the last 72 hours has enabled FanControl to start minimised and all fans follow their profile. Hope this helps.

Yes, I can confirm that is the solution for this issue

**Comment by Artuly** [comment] 2023-07-08 17:02
Having the same issue with the same MOBO as OP, sometimes it does sometimes not. Have to close it 1-3 times with task manager to get it working.

**Comment by Rem0o** [comment] 2023-07-23 17:38
For anyone having the "UI gets stuck and can't exit problem", I compiled a special version [here](https://github.com/Rem0o/FanControl.Releases/issues/1938#issuecomment-1646683977) with logs.  If anyone  with the problem could substitute their exe with the one from the link, and reproduce the problem, then sending the logs here, would help tons identifying where the problem is exactly.

**Comment by Kenshokram** [comment] 2023-07-27 10:48
I'm sorry that I didn't post here again, I was busy and got a bit overwhelmed by the amount of replies lol The issue has since stopped happening to me through the updates a while ago. I might open a new issue tho because the program doesn't seem to be able to handle windows 11 going to sleep and waking up, in the same way startup failed, but I haven't seen a thread about it.

**Comment by InterClaw** [comment] 2023-08-14 21:08
Really curious about what the problem was!

**Closed** 2023-09-26 14:47 UTC
Labels: next version
