### ISSUE TITLE
Handling of WM_CLOSE

### ISSUE THREAD

**Issue by t3t3** [Rem0o/FanControl.Releases#114] opened 2021-01-08 12:10 UTC
If the app receives a close signal (WM_CLOSE), it appears to act like when clicking the close button by hand - which usually means only the main window is going to hide.

I think, WM_CLOSE should be handled different from a (user) click on the close button of the main window.

So, for example, if you do a `taskkill /im FanControl.exe` the app still runs along; only `taskkill /f /im FanControl.exe` is going to shut it down - but in a hard way.

I expect this also to happen when logging off, or shutting down (though have not checked that!). If so, it would delay the logoff/shutdown, since Windows waits a certain amount of time for hung apps until it kills them off... again, I might be wrong in this regards.

**Comment by Rem0o** [comment] 2021-01-09 15:31
WM_CLOSE is a close window message. Since this runs as a background app, closing the UI doesn't close the app, which is expected behavior.

**Closed by Rem0o** 2021-01-09 15:31 UTC

**Comment by t3t3** [comment] 2021-01-09 17:16
You are probably right; I just tried to find a way to close the App "the right way" via scripting; `taskkill /f` _will_ close it, but since this happens forcefully, it leaves the tray icon behind (in other words this is directly related to my feature request, nothing that casual users will ever stumble upon ;)
