### ISSUE TITLE
[Feature Request] running program/.exe trigger/offset.

### ISSUE THREAD

**Issue by 0xdcb** [Rem0o/FanControl.Releases#1800] opened 2023-05-28 06:18 UTC
I would love to have the ability to trigger an action if a particular exe starts. For example, if "call of duty.exe" is running all my fans run at 100% to ensure maximum performance.

**Comment by Rem0o** [comment] 2023-05-28 17:00
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/97

**Closed by Rem0o** 2023-05-28 17:00 UTC
