### ISSUE TITLE
Fan Control doesn't work properly on Windows 10 start

### ISSUE THREAD

**Issue by andrea75** [Rem0o/FanControl.Releases#70] opened 2020-11-13 23:41 UTC
Hi, I have a little (big) problem... all works like a charme, but only if I lunch the app manually. If I select the automatic Windows startup, all fans works at fixed speed. The program start correctely, because I see the tray icon and I can open completely clicking on it, but to take the speed control, I have to close the app and open manually again. 

I see that there is a 30 seconds delay, but is not depend from  it, because after a lot of minutes nothing change until, as I said before, I restart the app manually. 

I use a Gigabyte 970a-ud3 motherboard and Windows 10 64bit.

Thanks

**Comment by NCHlab** [comment] 2020-11-19 12:31
I have this same issue.

I am only controlling my GPU fans, however upon startup (via windows scheduler), Fan Control is not controlling my fans.

Running latest version of FC (v57)

![image](https://user-images.githubusercontent.com/32630046/99666592-1527f080-2a63-11eb-9d96-c7e8baced6b9.png)

**Comment by Rem0o** [comment] 2020-11-19 14:51
Quick question: if you are in that state where it doesn't control your fans and you heat up your GPU, does it eventually take over?

**Comment by NCHlab** [comment] 2020-11-19 18:22
Tested it now and it seems it controls the fans when gaming, but when I exit, it goes back to 30% and does not follow the fan trend (fan should be at 0%)

**Comment by a-lukasiak** [comment] 2020-11-24 21:59
I'm seeing the same issue with my GPU (RTX 3080) fans. When I start the app, they spin up to 30% and stay at that level even they should be at 0% per my custom curve. 

The only way to get them to follow the curve is to manually turn the fans off and then on again (the green switch on the fan card). Once I do that, all is fine, but it will still go back to 30% after some time and I have to "reset" it again.

![image](https://user-images.githubusercontent.com/38924451/100156094-a5719580-2ea8-11eb-88d1-bf05761be737.png)

![image](https://user-images.githubusercontent.com/38924451/100156111-ab677680-2ea8-11eb-8a79-4486e8eb81d5.png)

![image](https://user-images.githubusercontent.com/38924451/100156132-b0c4c100-2ea8-11eb-8d47-342c83d21655.png)

**Comment by Rem0o** [comment] 2020-11-24 22:12
MSI Afterburner, EVGA Precision X running or similar?

**Comment by NCHlab** [comment] 2020-11-24 22:13
I do have MSI Afterburner running

**Comment by Rem0o** [comment] 2020-11-24 22:14
> I do have MSI Afterburner running

If you eliminate that variable, same issue?

**Comment by NCHlab** [comment] 2020-11-24 22:58
I stopped MSI from running on startup and restarted my pc.

Fans were still stuck at 30%, I then started MSI and it seems to have moved to 0% now..

**Comment by ShallowSquire** [comment] 2020-11-25 04:45
> I stopped MSI from running on startup and restarted my pc.
> 
> Fans were still stuck at 30%, I then started MSI and it changed to 0%..

MSI Afterburner’s lowest fan speed is locked to 30%. I would make sure you don’t have the “user defined fan control” option enabled.

**Comment by a-lukasiak** [comment] 2020-11-25 12:34
I tried disabling MSI Afterburner, but it doesn't seem to help. Still seeing 30% fan speed when it should be 0%.

More often than not, it happens when:

- The PC wakes up from sleep
- I stop running a high GPU workload (such as a game) and the GPU is cooling down. The fans gradually slow down, but they only go down to 30% rather than 0%. They should be at 0% at 45 C and below, but instead they're still at 30%, even at 35 C.

**Comment by Rem0o** [comment] 2020-11-25 14:06
If you apply a "Flat" fan curve set at anything below 30%, does it stay at that value or does the GPU has a mind of its own to set it back to 30?

**Comment by ShallowSquire** [comment] 2020-11-25 14:15
> I tried disabling MSI Afterburner, but it doesn't seem to help. Still seeing 30% fan speed when it should be 0%.
> 
> More often than not, it happens when:
> 
> * The PC wakes up from sleep
> * I stop running a high GPU workload (such as a game) and the GPU is cooling down. The fans gradually slow down, but they only go down to 30% rather than 0%. They should be at 0% at 45 C and below, but instead they stop at 30%, even at 35 C.

My next suggestion is to uninstall Afterburner, reboot, and reinstall your graphics card drivers. That should get everything to run at the card’s default fan curve.

**Comment by ShallowSquire** [comment] 2020-11-25 23:32
> If you apply a "Flat" fan curve set at anything below 30%, does it stay at that value or does the GPU has a mind of its own to set it back to 30? Is this only on 30XX series cards?

The issue is not the GPU, Afterburner locks the lowest fan curve to 30%. So even if the card’s BIOS itself has a 0% fan curve, if you set any type of custom fan curve in Afterburner it will always override the card’s fan curve.

**Comment by NCHlab** [comment] 2020-11-26 00:12
> 
> 
> > I stopped MSI from running on startup and restarted my pc.
> > Fans were still stuck at 30%, I then started MSI and it changed to 0%..
> 
> MSI Afterburner’s lowest fan speed is locked to 30%. I would make sure you don’t have the “user defined fan control” option enabled.

I don't have that option enabled.

**Comment by Rem0o** [comment] 2020-11-26 00:20
One thing is for sure, FanControl isn't the one that applies the 30% value. Something else is.

**Comment by a-lukasiak** [comment] 2020-11-29 14:04
You're right, I think this is an issue with NVIDIA drivers. I noticed that the same thing happens if I turn off fan control on rely on the curve I set in MSI Afterbuner.

More context here:
https://www.reddit.com/r/gigabytegaming/comments/jktz9x/gigabyte_3080_gaming_oc_not_following_msi/

People were able to work around this by downgrading their drivers, but I think I'm just going to wait for a fix. I can live with the fans going at 30% in idle as long as I know this is temporary and fixable.

Thanks for looking into this @Rem0o! I love the app.

**Comment by LucasIcarus** [comment] 2021-01-30 17:50
> You're right, I think this is an issue with NVIDIA drivers. I noticed that the same thing happens if I turn off Fan Control and rely on the curve I set in MSI Afterbuner.
> 
> More context here:
> https://www.reddit.com/r/gigabytegaming/comments/jktz9x/gigabyte_3080_gaming_oc_not_following_msi/
> 
> People were able to work around this by downgrading their drivers, but I think I'm just going to wait for a fix. I can live with the fans going at 30% in idle as long as I know this is temporary and fixable.
> 
> Thanks for looking into this @Rem0o! I love the app.

Hey, any update on this issue? I have latest driver@460.40 and RTX3090, the 30% low threshhold was still there..

extract some werrid log from Fancontrol

when stays 30%
```log
Cooler Settings

 Status: NOT_SUPPORTED

Fan Coolers Status

 Items[0].Type: 1
 Items[0].CurrentRpm: 1320
 Items[0].CurrentMinLevel: 30
 Items[0].CurrentMaxLevel: 100
 Items[0].CurrentLevel: 30
 Items[1].Type: 2
 Items[1].CurrentRpm: 1324
 Items[1].CurrentMinLevel: 30
 Items[1].CurrentMaxLevel: 100
 Items[1].CurrentLevel: 30
```

when switch Fancontrol GPU fan Controls off, trigger automatic stop

```log

Cooler Settings

 Status: NOT_SUPPORTED

Fan Coolers Status

 Items[0].Type: 1
 Items[0].CurrentRpm: 0
 Items[0].CurrentMinLevel: 30
 Items[0].CurrentMaxLevel: 100
 Items[0].CurrentLevel: 0
 Items[1].Type: 2
 Items[1].CurrentRpm: 0
 Items[1].CurrentMinLevel: 30
 Items[1].CurrentMaxLevel: 100
 Items[1].CurrentLevel: 0

```

Maybe figure where the CurrentMinLevel came from out can be helpful ?

**Comment by eduroca** [comment] 2021-03-06 19:11
I have a similar issue where when waking up from sleep, FanControl will report incorrect speeds (thousands of RPMs higher) for Chassis Fans, and won't be able to control their speeds. Refreshing sensors will throw an error.

Closing the application won't help.

The only way to fix it that I've found is to run HWMonitor. After that I can refresh sensors correctly.

This is on an Asus B450M-A Prime, running Windows 10. FanControl V. 70.

> 5/3/2021 11:49:37: Unhandled exception in FanControl v1.0.0.0
5/3/2021 11:49:37: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at FanControl.ViewModels.MainWindowViewModel.RefreshSensors()
   at FanControl.ViewModels.MainWindowViewModel.Refresh()
   at FanControl.ViewModels.MainWindowViewModel.<<RestoreApplicationState>b__119_10>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at FanControl.ViewModels.MainWindowViewModel.RefreshSensors()
   at FanControl.ViewModels.MainWindowViewModel.Refresh()
   at FanControl.ViewModels.MainWindowViewModel.<<RestoreApplicationState>b__119_10>d.MoveNext()<---

5/3/2021 11:49:37: System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at FanControl.ViewModels.MainWindowViewModel.RefreshSensors()
   at FanControl.ViewModels.MainWindowViewModel.Refresh()
   at FanControl.ViewModels.MainWindowViewModel.<<RestoreApplicationState>b__119_10>d.MoveNext()
5/3/2021 11:49:37: Unhandled exception in FanControl v1.0.0.0
5/3/2021 11:49:37: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at FanControl.ViewModels.MainWindowViewModel.RefreshSensors()
   at FanControl.ViewModels.MainWindowViewModel.Refresh()
   at FanControl.ViewModels.MainWindowViewModel.<<RestoreApplicationState>b__119_10>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at FanControl.ViewModels.MainWindowViewModel.RefreshSensors()
   at FanControl.ViewModels.MainWindowViewModel.Refresh()
   at FanControl.ViewModels.MainWindowViewModel.<<RestoreApplicationState>b__119_10>d.MoveNext()<---

5/3/2021 11:49:37: System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at FanControl.ViewModels.MainWindowViewModel.RefreshSensors()
   at FanControl.ViewModels.MainWindowViewModel.Refresh()
   at FanControl.ViewModels.MainWindowViewModel.<<RestoreApplicationState>b__119_10>d.MoveNext()

**Comment by pigsodomizer** [comment] 2021-03-24 21:23
I have the same issue as eduroca. I solved that (for the time being) by adding HWMonitor and FanControl to regedit to startup. As long as it's working I don't have any complaints.

**Comment by HollyD9** [comment] 2022-03-30 09:46
How can i start FanControl with windows? I dont get it... O_o
Bevore a week, it has worked properly. but now it doesn't work anymore.

**Comment by Gwyrdd87** [comment] 2022-06-06 20:46
Had the same issue. Copied the FanControl.exe file into the AutoStart folder manually and since then it starts up with windows. Hope this works for you guys as well.
Great little piece of software by the way. I love it!!!

**Comment by Rem0o** [comment] 2022-10-22 18:42
Added a multi-retry mechanism since, until all sensors are back.

**Closed by Rem0o** 2022-10-22 18:42 UTC
