### ISSUE TITLE
FC launches and is running but doesn't appear in status bar

### ISSUE THREAD

**Issue by benncarroll** [Rem0o/FanControl.Releases#239] opened 2021-05-20 14:22 UTC
Basically title. V79 latest, just reinstalled. Running some custom hardware, e.g. NZXT AIO exposed at /nzxt/, could be related. NZXT companion software NOT running and disabled.

Does not appear in Task Manager, DOES appear when using [ProcessExplorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer)

If more info is needed pls let me know. Cheers.

log.txt:
```
20/05/2021 11:56:36 PM: Unhandled exception in FanControl v1.0.0.0
20/05/2021 11:56:36 PM: System.ObjectDisposedException: Closed.
   at HidSharp.Platform.SysRefCountHelper.HandleAcquireIfOpenOrFail()
   at HidSharp.Platform.Windows.WinHidStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at LibreHardwareMonitor.Hardware.Controller.Nzxt.KrakenX3.SoftwareControlValueChanged(Control control)
   at LibreHardwareMonitor.Hardware.Control.set_ControlMode(ControlMode value)
   at LibreHardwareMonitor.Hardware.Control.SetSoftware(Single value)
   at FanControl.ViewModels.ControlViewModel.PeriodicUpdate()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
20/05/2021 11:59:06 PM: Unhandled exception in FanControl v1.0.0.0
20/05/2021 11:59:06 PM: System.IO.IOException: Event creation failed.
   at HidSharp.Platform.Windows.NativeMethods.CreateResetEventOrThrow(Boolean manualReset)
   at HidSharp.Platform.Windows.WinHidStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at LibreHardwareMonitor.Hardware.Controller.Nzxt.KrakenX3.Update()
   at FanControl.Domain.UpdateVisitor.VisitHardware(IHardware hardware)
   at LibreHardwareMonitor.Hardware.Computer.Traverse(IVisitor visitor)
   at FanControl.Domain.ComputerAccessLayer.UpdateSensors()
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by benncarroll** [comment] 2021-05-21 05:20
Update: This has happened multiple times now, doing various actions from Enabling manual mode, to editing a Mix sensor.

Nothing logged, hope the screenshot can be of some relevance!

![image](https://user-images.githubusercontent.com/29112976/119085905-f45b4a80-ba47-11eb-8cb3-b1b8017c0982.png)

**Comment by Rem0o** [comment] 2021-05-21 14:17
Seems to be a duplicate of https://github.com/Rem0o/FanControl.Releases/issues/231#issuecomment-845638086

**Comment by Rem0o** [comment] 2021-05-21 14:48
Well the HID byte stream to control the Nzxt device seems to get closed for a unknown reason. Are you able to debug C#? If so, put a debug version of https://github.com/LibreHardwareMonitor/LibreHardwareMonitor in there and attach to the process and see what's up with the stream.  I don't have a NZXT AIO, so I can't test that bit of code.

**Comment by benncarroll** [comment] 2021-05-25 23:10
Not experienced in doing so, but might see how far I get when I get the time.

**Comment by benncarroll** [comment] 2021-05-25 23:14
In the meantime, found something else that might help with stability! In such a situation where the control streams are closed for whatever reason, get a crash from empty list on an average. Maybe a test before DoActions() runs any code on the sequence to check if it currently has working elements would fix it?

I guess that then introduces the problem of what to pass on for that Average/Mix right?
Maybe last working value if that's still stored?


Log:
```
23/05/2021 9:29:45 AM: Unhandled exception in FanControl v1.0.0.0
23/05/2021 9:29:45 AM: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at FanControl.ViewModels.MixFanCurveViewModel.UpdateCurrentCommandTarget()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Closed** 2022-07-05 14:02 UTC
