### ISSUE TITLE
Linux Support and List of supported devices

### ISSUE THREAD

**Issue by Abyssgrowth** [Rem0o/FanControl.Releases#1806] opened 2023-06-02 20:29 UTC
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]
Just wanted to ask if this software is for windows only or supports linux also? And is there a list of supported devices, if so where?

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

**Comment by Rem0o** [comment] 2023-06-02 20:36
* No support for Linux. 
* There is no list for supported devices/motherboard. All code and information regarding hardware compatibility can be found here: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

**Comment by RokeJulianLockhart** [comment] 2023-09-25 16:36
This should be closed. This is merely a duplicate of https://github.com/Rem0o/FanControl.Releases/issues/535#issue-1169197832.

**Closed** 2023-09-25 21:10 UTC
