### ISSUE TITLE
Feature Request: Run as a service

### ISSUE THREAD

**Issue by WaningMemory** [Rem0o/FanControl.Releases#973] opened 2022-07-24 17:37 UTC
Feature request - allow fancontrol.exe to run as a service. This allows the PC to better survive unexpected power resets. 

Currently fancontrol.exe runs great in SYSTEM context but doing so prevents the UI from being used in the user's context.

**Comment by Rem0o** [comment] 2022-07-24 22:06
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/135

**Closed by Rem0o** 2022-07-24 22:06 UTC
