### ISSUE TITLE
Meldung Fehlernder Steuerungssensor seit 204

### ISSUE THREAD

**Issue by Lumumba76** [Rem0o/FanControl.Releases#2756] opened 2024-09-28 11:47 UTC
Ich bekomme diese Meldungen seit dem Update auf 204 und auch in 205
![Fan Control 205-1](https://github.com/user-attachments/assets/83cc9034-5790-4592-81f7-0fd60edc9685)
![Fan Control 205-2](https://github.com/user-attachments/assets/d2839178-23e0-4839-8bd2-053daf6c6424)
![Fan Control 205-3](https://github.com/user-attachments/assets/9ef69ad4-ead6-4a98-843b-8a622718bedb)

Log:
`28.09.2024 13:26:17: Try refresh failed. Retry count (6) exceeded.
Sensor validation failed.`

**Comment by Lumumba76** [comment] 2024-09-28 12:17
Nachdem ich eine komplett neue Konfiguration erstellt habe, funktioniert es wieder

**Comment by Rem0o** [comment] 2024-09-28 16:34
This error means at the time you saved your configuration, the program detected "N" sensors.   Now it is missing at least 1.  May be hardware change, LHM support regression, driver changes...  If nothing is actually missing from your configuration, you can simply "save" on top to remember the new count of sensors.

**Comment by VnnAmed** [comment] 2024-09-28 18:44
Hi, I have the same issue on one of my machines. It was updated today to 205 and Fan Control lost one of the sensors. I've re-downloaded it and tried to re-configure from scratch, but this time it only sees my GPU and detects no sensors at all on the motherboard. Mobo is Crosshair VII Hero from Asus.

**Comment by Nomarix** [comment] 2024-09-29 09:59
Unfortunatly for me the same. Fan is not detected and also missing in overview.
No HW, no Bios update or configuration change, happend with update 205.
Fan is spinning, so I assume no HW failure.
Reload after boot also does not help.
Mainboard is a Gigabyte Gaming X Z790

![grafik](https://github.com/user-attachments/assets/d4c265bf-ff69-48b5-83c3-e74e02aed31f)

**Comment by Faggi11** [comment] 2024-09-30 13:55
![Screenshot 2024-09-30_vers 205](https://github.com/user-attachments/assets/c864ffc4-f63b-45ca-aaaa-a26cba188809)

**Comment by Faggi11** [comment] 2024-10-01 17:05
I tried further new configs, just with "CPU, GPU & Motherboard" in the sensor settings, i dont get the missing fan/sensor.
I just found in the sensor settings the copy icon for LHM and these seems different in my case for v204 and v205. In v204 it looks "good", in v205 "not good" 'cause the missing fan.
I have no clue about this, but maybe it could help.
![copy from LHM v204](https://github.com/user-attachments/assets/61c9661c-45ee-4913-9af8-a31ee6f02554)
![copy from LHM v205](https://github.com/user-attachments/assets/928b912f-9c03-44c4-9d2d-4b0de263c707)

Just for the my work, it is good and working for me with v204 (oh and i didnt update BIOS/drivers the last days, last driver was on 12th Sep. Steelseries Mouse).
Thanks in advance

**Comment by thegame4craft** [comment] 2024-10-02 19:13
@Lumumba76 I made a pull request a few weeks ago that was a few days ago merged. Let me know which mainboard do you have so I can correct that...

**Comment by Rem0o** [comment] 2024-10-08 17:41
V206

**Closed by Rem0o** 2024-10-08 17:41 UTC

**Comment by Faggi11** [comment] 2024-10-08 18:04
Uuuuh, i will check that, thanks

**Comment by Faggi11** [comment] 2024-10-08 18:19
> V206

Sorry, same for me as before ..... with starting a new config, it still "skips" the 4th fan

**Comment by Faggi11** [comment] 2024-10-08 19:48
As i mentioned obove, i original use the portable version, which was updated to v205 and 2 hours ago to v206. After i updated this to v205 and i realise the missing fan #4, i installed the setup version with v204 to use FC as before, which i now use and doesnt updating it.
But i will get the v206 as a portable again, as a fresh one to see any difference

**Comment by Faggi11** [comment] 2024-10-08 20:17
No, no difference with a new fresh portable version, same missing fan #4.

**Comment by Faggi11** [comment] 2024-10-10 13:23
Oh, just a little detail, which i perhaps skip by reading ...... the updated v206 because of "it8665e" ..... my board has _it8689e_ 
This could maybe the problem, which the v206 doesnt solve my issue!?

**Comment by thegame4craft** [comment] 2024-10-10 19:12
If your mainboard uses it8689e I think the issue isn't fixed by 206 or any other version.

**Comment by Faggi11** [comment] 2024-10-10 19:37
Hmmm, maybe i did something wrong with the hwinfo plugin, but it doesnt show the missing fan ....... i use already hwinfo since ....  there is everything fine with the sensors/fans.
I will stay with the v204 untill i get this to work with future versions
Thanks so far

**Comment by Faggi11** [comment] 2024-10-30 00:26
For the completeness in my case, i just found out today, that ('cause i hide the speed cards) if the speed cards are visible, it shows me the missing fan. So this gives me the question, why doesnt detects FC the "missing" control card.
I tried this today with the new v207.
Any thoughts?
![test v207](https://github.com/user-attachments/assets/3d5bd4c6-b08f-4f9f-a798-c365df02294c)

**Comment by Rem0o** [comment] 2024-10-30 01:38
Found the issue in LHM:

Problem is here:
![image](https://github.com/user-attachments/assets/970d41bd-3cd1-401f-a65e-3f4c682d4723)

Previously it used the default IT8689E config which has 6, but the specific implementation for the motherboard that was added only has 5 fans.

**Comment by Faggi11** [comment] 2024-10-30 15:37
Okay, good for the "catch" of the missing ..... and what does that mean for us? Do we have to wait for LHM check/update or so?
Maybe it is a stupid question, but i have to less clue about software stuff respectively in english understanding ;)

**Comment by Rem0o** [comment] 2024-10-30 15:43
There is a PR:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1508

**Comment by StevenHachel** [comment] 2024-10-31 19:35
Version: 207
Nothing works here anymore. Very annoying.
I just got an update and now nothing works anymore.

MSI: MPG 550
CPU: AMD Ryzen 7 5800X
GPU: NVIDIA GeFOrce RTX 3060 TI
![grafik](https://github.com/user-attachments/assets/ff564caa-a3da-4aa7-b194-173c589628bd)

**Comment by Faggi11** [comment] 2024-11-02 16:38
@StevenHachel I would recommend, as I did, for the first, to use older version, I still using v204

**Comment by Faggi11** [comment] 2024-11-16 14:10
> There is a PR: [LibreHardwareMonitor/LibreHardwareMonitor#1508](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1508)

Heyho, i would leave the info, that with the v208 now, the detection of ALL fans/sensors are now recovered in my case.
Thanks :)
