### ISSUE TITLE
GPU Temperature not detected after AMD Windows 11 Driver update

### ISSUE THREAD

**Issue by MailoBaca** [Rem0o/FanControl.Releases#925] opened 2022-07-06 21:58 UTC
Temperature source list does not show GPU at all after updating to AMD Windows 11 driver 30.0.21023.1015

**Comment by Rem0o** [comment] 2022-07-06 23:11
Possible duplicate of https://github.com/Rem0o/FanControl.Releases/issues/881?

**Comment by mandel99** [comment] 2022-07-16 20:06
I have same problem on RX580 all is up to date.
Windows 11 22H2 (25151.1010)
AMD Adrenalin 22.6.1 
Temperature is visible in AMD adrenalin, windows task manager and HWiNFo (even GPU-Z have same problem)
<img width="168" alt="tmp" src="https://user-images.githubusercontent.com/4213037/179370497-e2cd7159-f97f-4222-9a60-db4412e30855.png">

**Comment by Rem0o** [comment] 2023-02-11 17:03
https://github.com/Rem0o/FanControl.ADLX

**Closed by Rem0o** 2023-02-11 17:03 UTC
