### ISSUE TITLE
Error on loading existing configuration adter v182 update.

### ISSUE THREAD

**Issue by renevdvorst** [Rem0o/FanControl.Releases#2358] opened 2024-03-14 14:29 UTC
**Describe the bug**
After updating to v182 the user config can't be loaded, automatically nor manually. I get a popup saying: "Could not load the configuration. An unexpected error has been added to the log file" Clicking on Ok or cancel just repeats this message. The config seems to be overridden now with a default however the backup one also throws this error.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
14/03/2024 15:14:46: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.FlatFanCurveViewModel.GetCommand()
   at FanControl.Domain.FanCurves.MixFanCurve.UpdateCommand(Single _)
   at FanControl.ViewModels.MixFanCurveViewModel.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
14/03/2024 15:14:47: Unhandled exception in FanControl v182.0.0.0
14/03/2024 15:14:47: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.FlatFanCurveViewModel.GetCommand()
   at FanControl.Domain.FanCurves.MixFanCurve.UpdateCommand(Single _)
   at FanControl.ViewModels.MixFanCurveViewModel.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Relevant hardware specs and setup**
Mainboard: MAG B550M MORTAR WIFI
CPU: Ryzen 5600X
GPU: AMD RX6800

**Comment by renevdvorst** [comment] 2024-03-14 14:38
I see now a similar issue was opened while I was writing this so feel free to close.

**Comment by Rem0o** [comment] 2024-03-14 15:03
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/2357#issuecomment-1997593372

**Closed by Rem0o** 2024-03-14 15:03 UTC
