### ISSUE TITLE
CPU temp source is not present

### ISSUE THREAD

**Issue by TPZSPARROW** [Rem0o/FanControl.Releases#74] opened 2020-11-17 06:25 UTC
AMD 5800x on an ASUS X570 TUF Plus (Wifi)

![image](https://user-images.githubusercontent.com/74585990/99354104-9e200b80-285a-11eb-9884-680893bb442f.png)

none of the available temperature readings correlate with CPU temperature.

**Comment by FloRup** [comment] 2020-11-17 08:03
Duplicate of #63

**Comment by Rem0o** [comment] 2020-11-17 20:19
https://github.com/Rem0o/FanControl.Releases/releases/tag/V57

**Closed** 2020-11-17 20:20 UTC
