### ISSUE TITLE
No CPU temperature values for Zen 5

### ISSUE THREAD

**Issue by rony-x2** [Rem0o/FanControl.Releases#2740] opened 2024-09-19 22:07 UTC
Hello,
I have a new Ryzen 9950X and since the CPU change from the 7950X, the CPU does not display any temperature values.

I was able to work around it by selecting the temperature values of the motherboard, but I would prefer to use the exact values of the CPU.

Screenshots attached.

I am currently using FanControl v203

![20240919_233643-Verbessert-RR](https://github.com/user-attachments/assets/fa5f592d-9a48-4e81-91e8-c2d0563d631d)
![Screenshot 2024-09-20 000631](https://github.com/user-attachments/assets/4be1ec74-abec-4324-ae96-8cad4c230a74)
![Screenshot 2024-09-20 000608](https://github.com/user-attachments/assets/139e7714-758b-4ab8-96d3-f0c7b1ce1a57)

**Comment by Rem0o** [comment] 2024-09-20 01:53
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/2733

**Closed by Rem0o** 2024-09-20 01:53 UTC
