### ISSUE TITLE
Update for 174 fails with error that Newtonsoft.Json.dll can't be written over due to it being in use.

### ISSUE THREAD

**Issue by GuruSR** [Rem0o/FanControl.Releases#2142] opened 2023-11-22 12:58 UTC
**Describe the bug**
During the update to 174, the error came up that Newtonsoft.Json.dll was in use and couldn't be replaced, causing the Updater.exe to fail to update.

There is no log needed nor screenshot, the fix is as follows:

Manually browse to where you have FanControl, then delete Newtonsoft.Json.dll and run Updater.exe, the update successfully finishes.

I didn't close this in the event the Updater can be improved to avoid this situation.

**Comment by JensEngels** [comment] 2023-11-22 13:05
Had the same issue, this solution worked perfectly! Thank you :)

**Comment by Rem0o** [comment] 2023-11-22 13:07
The updater exe uses Newstonsoft and the latest version I uploaded got flagged. As Defender yoinks the process, it leaves somehow a handle to the dll subsequently the dll can't be replaced. 

Will close as duplicate of https://github.com/Rem0o/FanControl.Releases/issues/2135

**Closed by Rem0o** 2023-11-22 13:07 UTC

**Comment by GuruSR** [comment] 2023-11-23 05:52
Actually, Defender didn't do anything to either file, no complaint about them (possibly due to an updated signature file at the time).  What I did was watch the open file count (using OpenedFilesView) on the Updater.exe and it was using the library in question, so it couldn't overwrite it, because it was using it.
