### ISSUE TITLE
is there anyway to get this running on linux?

### ISSUE THREAD

**Issue by catfrightening** [Rem0o/FanControl.Releases#710] opened 2022-04-29 18:34 UTC
linux users would love a linux version. an appimage file would be so useful. your software is so powerful.

**Comment by Rem0o** [comment] 2022-04-29 18:37
The backend implementation required for this to run on linux would be completely different from the one I'm using for Windows. The UI could be partly reused, but the backend would be a whole new project.

**Comment by Rem0o** [comment] 2022-05-13 21:08
Duplicate of #535

**Closed by Rem0o** 2022-05-13 21:08 UTC
